### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by GO-Loc-GO** [moonD4rk/HackBrowserData#100]
Met the following problems during the execution of hack-browser-data.exe on win10 64-bit system:
![fbd30a97be46d8c874a8920bedbadb1](https://user-images.githubusercontent.com/63333266/141102862-5d30ca70-e7fc-4d41-a2b3-f7627a95475c.png)
Basically, the first line of Chinese says the file is currently used by another process and can not be accessed; the latter says access is denied.
A blue box would also jump out for the second message saying that the program could not be run on this computer, please enquire on the developer.
Not sure what's happening...
Looking forward to some reply.

**Comment by moonD4rk** [comment]
Please check whether the `Folder Protection` is turned on, some ant-ivirus software has this featuer.
