### ISSUE TITLE
cmd语法

### ISSUE THREAD

**Issue by c3poo** [moonD4rk/HackBrowserData#102]
./HackBrowser.exe -b chrome -p 'C:\Users\Administrator\AppData\Local\Google\Chrome\User Data\Profile 1'

目标机器把powershell阻止了，请问老师 cmd 下的语法应该是怎样？

**Comment by moonD4rk** [comment]
use Double quotes `"`
try this command 
```
HackBrowser.exe -b chrome -p "C:\Users\ Administrator\AppData\Local\Google\Chrome\User Data\Default"
```

**Comment by c3poo** [comment]
Thank you very much
