### ISSUE TITLE
warning when build on windows 10

### ISSUE THREAD

**Issue by Phuong39** [moonD4rk/HackBrowserData#103]
# github.com/mattn/go-sqlite3                                                                            
sqlite3-binding.c: In function 'sqlite3SelectNew':                                                       
sqlite3-binding.c:129019:10: warning: function may return address of local variable [-Wreturn-local-addr]
129019 |   return pNew;                                                                                  
       |          ^~~~
sqlite3-binding.c:128979:10: note: declared here
128979 |   Select standin;
       |          ^~~~~~~

==========================
all .csv file have random column have random name (ex: 
chrome_password.csv : QoWJyY3V,NVYpZ7ht,IfHzGZiO,EtIP2BI3
chrome_cookie.csv: FqlOsfmu,NX4QOYkP,ZajoU5Q2,ZyX4bNBf,VOBmxR5G,AcqHYqrO,AXWDloTC,Vbzl53Ym,ElYv41bL,AYam4ZAJ
)

**Comment by moonD4rk** [comment]
How about the v0.3.8 download from [github release](https://github.com/moonD4rk/HackBrowserData/releases/tag/v0.3.8), Does the same problem exist?

**Comment by Phuong39** [comment]
i run on newest release v0.3.7,

**Comment by moonD4rk** [comment]
> i run on newest release v0.3.7,

I fixed this issue by upgrading the go-sqlite3 version to 1.4.9, you can download [v0.3.7]( https://github.com/moonD4rk/HackBrowserData/releases/tag/untagged-5a0b9312a5a8d9b41f1f) to test if this bug exists.
