### ISSUE TITLE
Problems with chrome cookies

### ISSUE THREAD

**Issue by jaday88** [moonD4rk/HackBrowserData#104]
**Describe the bug**
Use `./hack-browser-data -vv` paste result here

**Desktop (please complete the following information):**
 - OS Name: Windows 10 Pro
 - Browser Name: Chrome
 - Browser Version: 96.0.4664.93  64 bit

**Additional context**

Does not load chrome cookies, also completely ignores the Yandex browser, cookies are not imported in json or svc if you convert them to netscape

**Comment by moonD4rk** [comment]
Thanks for submitting this Issuse, it looks like chrome has changed the file names of `cookies` and `bookmarks` in a recent update.

**Comment by c3poo** [comment]
Cookies are separately placed in the network folder by the new version of Chrome
I also found this problem yesterday

**Comment by jaday88** [comment]
> Спасибо за отправку этого сообщения, похоже, что chrome изменил имена файлов `cookies`в недавнем обновлении.

json or svc cookies are not imported into the browser, tried many browser extensions. How can I make it automatically pack them into a zip folder when launching the exe?

**Comment by moonD4rk** [comment]
> > Спасибо за отправку этого сообщения, похоже, что chrome изменил имена файлов `cookies`в недавнем обновлении.
> 
> json or svc cookies are not imported into the browser, tried many browser extensions. How can I make it automatically pack them into a zip folder when launching the exe?

I would release v0.3.8 recently and will fix the issus then.

**Comment by jaday88** [comment]
Please can you name a program that will efficiently convert .csv cookies to netscape or json. At the moment I tried several online converters to do this, but after conversion I can't load the cookie into the browser

**Comment by jaday88** [comment]
> > > Спасибо за отправку этого сообщения, похоже, что chrome изменил имена файлов `cookies`в недавнем обновлении.
> > 
> > 
> > json or svc cookies are not imported into the browser, tried many browser extensions. How can I make it automatically pack them into a zip folder when launching the exe?
> 
> I would release v0.3.8 recently and will fix the issus then.

Please can you name a program that will efficiently convert .csv cookies to netscape or json. At the moment I tried several online converters to do this, but after conversion I can't load the cookie into the browser

**Comment by moonD4rk** [comment]
@jaday88 It's already support json output,  try `./hack-browser-data.exe -f json ` command.

**Comment by jaday88** [comment]
> @jaday88 It's already support json output, try `./hack-browser-data.exe -f json ` command.

It doesn't work, he saved in json, but they don't open, only one at a time. What is the easiest way to download the cookies that the program downloaded, uploaded to another browser?

**Comment by jaday88** [comment]
> @jaday88 It's already support json output, try `./hack-browser-data.exe -f json ` command.

It cannot find the path to the encryption keys
https://prnt.sc/23oaxj1

**Comment by jaday88** [comment]
This is what the program gives out, it can't find the encryption keys

cmd.go:69: error Brave secret key path is empty
cmd.go:69: error Opera secret key path is empty
[x]:  Get 0 passwords, filename is results/microsoft_edge_password.csv
[x]:  Get 0 credit cards, filename is results/microsoft_edge_credit.csv
[x]:  Get 29 cookies, filename is results/microsoft_edge_cookie.csv
[x]:  Get 40 history, filename is results/microsoft_edge_history.csv
[x]:  Get 2 download history, filename is results/microsoft_edge_download.csv
cmd.go:69: error OperaGX secret key path is empty
[x]:  Get 0 credit cards, filename is results/chrome_credit.csv
[x]:  Get 174 bookmarks, filename is results/chrome_bookmark.csv
[x]:  Get 3883 history, filename is results/chrome_history.csv
[x]:  Get 104 download history, filename is results/chrome_download.csv
[x]:  Get 4 passwords, filename is results/chrome_password.csv
cmd.go:69: error Chrome Beta secret key path is empty
cmd.go:69: error Vivaldi secret key path is empty
cmd.go:69: error CocCoc secret key path is empty
cmd.go:69: error Yandex secret key path is empty
cmd.go:69: error Chromium secret key path is empty

**Comment by moonD4rk** [comment]
@jaday88 use `./hack-browser-data -vv` show verbose

**Comment by jaday88** [comment]
C:\Programms\11111\222\hack-browser-data--windows-64bit>hack-browser-data--windows-64bit.exe -vv
browser.go:207: debug Firefox Beta find cookie file failed, ERR:find cookies.sqlite failed
browser.go:207: debug Firefox Beta find history file failed, ERR:find places.sqlite failed
browser.go:207: debug Firefox Beta find download file failed, ERR:find places.sqlite failed
browser.go:201: debug Firefox Beta find password file failed, ERR:find logins.json failed
browser.go:207: debug Firefox Beta find bookmark file failed, ERR:find places.sqlite failed
cmd.go:69: error Chromium secret key path is empty
browser.go:154: debug Chromium find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug Chromium find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug Chromium find cookie file failed, ERR:find Cookies failed
browser.go:154: debug Chromium find history file failed, ERR:find History failed
browser.go:154: debug Chromium find download file failed, ERR:find History failed
browser.go:154: debug Chromium find password file failed, ERR:find Login Data failed
browser.go:154: debug 360speed find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug 360speed find cookie file failed, ERR:find Cookies failed
browser.go:154: debug 360speed find history file failed, ERR:find History failed
browser.go:154: debug 360speed find download file failed, ERR:find History failed
browser.go:154: debug 360speed find password file failed, ERR:find Login Data failed
browser.go:154: debug 360speed find creditcard file failed, ERR:find Web Data failed
cmd.go:69: error Vivaldi secret key path is empty
browser.go:154: debug Vivaldi find download file failed, ERR:find History failed
browser.go:154: debug Vivaldi find password file failed, ERR:find Login Data failed
browser.go:154: debug Vivaldi find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug Vivaldi find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug Vivaldi find cookie file failed, ERR:find Cookies failed
browser.go:154: debug Vivaldi find history file failed, ERR:find History failed
cmd.go:69: error OperaGX secret key path is empty
browser.go:154: debug OperaGX find password file failed, ERR:find Login Data failed
browser.go:154: debug OperaGX find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug OperaGX find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug OperaGX find cookie file failed, ERR:find Cookies failed
browser.go:154: debug OperaGX find history file failed, ERR:find History failed
browser.go:154: debug OperaGX find download file failed, ERR:find History failed
browser.go:207: debug Firefox Dev find bookmark file failed, ERR:find places.sqlite failed
browser.go:207: debug Firefox Dev find cookie file failed, ERR:find cookies.sqlite failed
browser.go:207: debug Firefox Dev find history file failed, ERR:find places.sqlite failed
browser.go:207: debug Firefox Dev find download file failed, ERR:find places.sqlite failed
browser.go:201: debug Firefox Dev find password file failed, ERR:find logins.json failed
cmd.go:69: error Chrome Beta secret key path is empty
browser.go:154: debug Chrome Beta find cookie file failed, ERR:find Cookies failed
browser.go:154: debug Chrome Beta find history file failed, ERR:find History failed
browser.go:154: debug Chrome Beta find download file failed, ERR:find History failed
browser.go:154: debug Chrome Beta find password file failed, ERR:find Login Data failed
browser.go:154: debug Chrome Beta find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug Chrome Beta find bookmark file failed, ERR:find Bookmarks failed
browser.go:158: debug Microsoft Edge find history File Success
browser.go:158: debug Microsoft Edge find download File Success
browser.go:158: debug Microsoft Edge find password File Success
browser.go:158: debug Microsoft Edge find creditcard File Success
browser.go:154: debug Microsoft Edge find bookmark file failed, ERR:find Bookmarks failed
browser.go:158: debug Microsoft Edge find cookie File Success
[x]:  Get 70 history, filename is results/microsoft_edge_history.csv
[x]:  Get 0 download history, filename is results/microsoft_edge_download.csv
[x]:  Get 1 passwords, filename is results/microsoft_edge_password.csv
[x]:  Get 0 credit cards, filename is results/microsoft_edge_credit.csv
[x]:  Get 42 cookies, filename is results/microsoft_edge_cookie.csv
browser.go:154: debug qq find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug qq find cookie file failed, ERR:find Cookies failed
browser.go:154: debug qq find history file failed, ERR:find History failed
browser.go:154: debug qq find download file failed, ERR:find History failed
browser.go:154: debug qq find password file failed, ERR:find Login Data failed
browser.go:154: debug qq find creditcard file failed, ERR:find Web Data failed
cmd.go:69: error Opera secret key path is empty
browser.go:154: debug Opera find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug Opera find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug Opera find cookie file failed, ERR:find Cookies failed
browser.go:154: debug Opera find history file failed, ERR:find History failed
browser.go:154: debug Opera find download file failed, ERR:find History failed
browser.go:154: debug Opera find password file failed, ERR:find Login Data failed
browser.go:211: debug Firefox find bookmark file success
browser.go:211: debug Firefox find cookie file success
browser.go:211: debug Firefox find history file success
browser.go:211: debug Firefox find download file success
browser.go:201: debug Firefox find password file failed, ERR:find logins.json failed
[x]:  Get 5 bookmarks, filename is results/firefox_bookmark.csv
[x]:  Get 38 cookies, filename is results/firefox_cookie.csv
parse.go:416:  sql: Scan error on column index 2, name "last_visit_date": converting NULL to int64 is unsupported
parse.go:416:  sql: Scan error on column index 2, name "last_visit_date": converting NULL to int64 is unsupported
parse.go:416:  sql: Scan error on column index 2, name "last_visit_date": converting NULL to int64 is unsupported
parse.go:416:  sql: Scan error on column index 2, name "last_visit_date": converting NULL to int64 is unsupported
parse.go:416:  sql: Scan error on column index 2, name "last_visit_date": converting NULL to int64 is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416:  sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
[x]:  Get 80 history, filename is results/firefox_history.csv
[x]:  Get 3 download history, filename is results/firefox_download.csv
browser.go:207: debug Firefox Nightly find bookmark file failed, ERR:find places.sqlite failed
browser.go:207: debug Firefox Nightly find cookie file failed, ERR:find cookies.sqlite failed
browser.go:207: debug Firefox Nightly find history file failed, ERR:find places.sqlite failed
browser.go:207: debug Firefox Nightly find download file failed, ERR:find places.sqlite failed
browser.go:201: debug Firefox Nightly find password file failed, ERR:find logins.json failed
browser.go:158: debug Brave find password File Success
browser.go:158: debug Brave find creditcard File Success
browser.go:154: debug Brave find bookmark file failed, ERR:find Bookmarks failed
browser.go:158: debug Brave find cookie File Success
browser.go:158: debug Brave find history File Success
browser.go:158: debug Brave find download File Success
[x]:  Get 0 passwords, filename is results/brave_password.csv
[x]:  Get 0 credit cards, filename is results/brave_credit.csv
[x]:  Get 344 cookies, filename is results/brave_cookie.csv
[x]:  Get 34 history, filename is results/brave_history.csv
[x]:  Get 0 download history, filename is results/brave_download.csv
cmd.go:69: error CocCoc secret key path is empty
browser.go:154: debug CocCoc find download file failed, ERR:find History failed
browser.go:154: debug CocCoc find password file failed, ERR:find Login Data failed
browser.go:154: debug CocCoc find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug CocCoc find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug CocCoc find cookie file failed, ERR:find Cookies failed
browser.go:154: debug CocCoc find history file failed, ERR:find History failed
browser.go:207: debug Firefox ESR find download file failed, ERR:find places.sqlite failed
browser.go:201: debug Firefox ESR find password file failed, ERR:find logins.json failed
browser.go:207: debug Firefox ESR find bookmark file failed, ERR:find places.sqlite failed
browser.go:207: debug Firefox ESR find cookie file failed, ERR:find cookies.sqlite failed
browser.go:207: debug Firefox ESR find history file failed, ERR:find places.sqlite failed
browser.go:158: debug Chrome find download File Success
browser.go:158: debug Chrome find password File Success
browser.go:158: debug Chrome find creditcard File Success
browser.go:158: debug Chrome find bookmark File Success
browser.go:154: debug Chrome find cookie file failed, ERR:find Cookies failed
browser.go:158: debug Chrome find history File Success
[x]:  Get 4 download history, filename is results/chrome_download.csv
[x]:  Get 5 passwords, filename is results/chrome_password.csv
[x]:  Get 0 credit cards, filename is results/chrome_credit.csv
[x]:  Get 4 bookmarks, filename is results/chrome_bookmark.csv
[x]:  Get 136 history, filename is results/chrome_history.csv
cmd.go:69: error Yandex secret key path is empty
browser.go:154: debug Yandex find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug Yandex find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug Yandex find cookie file failed, ERR:find Cookies failed
browser.go:154: debug Yandex find history file failed, ERR:find History failed
browser.go:154: debug Yandex find download file failed, ERR:find History failed
browser.go:154: debug Yandex find password file failed, ERR:find Login Data failed

**Comment by jaday88** [comment]
> 
C:\Programms\11111\222\hack-browser-data--windows-64bit>hack-browser-data--windows-64bit.exe -vv
browser.go:207: debug Firefox Beta find cookie file failed, ERR:find cookies.sqlite failed
browser.go:207: debug Firefox Beta find history file failed, ERR:find places.sqlite failed
browser.go:207: debug Firefox Beta find download file failed, ERR:find places.sqlite failed
browser.go:201: debug Firefox Beta find password file failed, ERR:find logins.json failed
browser.go:207: debug Firefox Beta find bookmark file failed, ERR:find places.sqlite failed
cmd.go:69: error Chromium secret key path is empty
browser.go:154: debug Chromium find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug Chromium find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug Chromium find cookie file failed, ERR:find Cookies failed
browser.go:154: debug Chromium find history file failed, ERR:find History failed
browser.go:154: debug Chromium find download file failed, ERR:find History failed
browser.go:154: debug Chromium find password file failed, ERR:find Login Data failed
browser.go:154: debug 360speed find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug 360speed find cookie file failed, ERR:find Cookies failed
browser.go:154: debug 360speed find history file failed, ERR:find History failed
browser.go:154: debug 360speed find download file failed, ERR:find History failed
browser.go:154: debug 360speed find password file failed, ERR:find Login Data failed
browser.go:154: debug 360speed find creditcard file failed, ERR:find Web Data failed
cmd.go:69: error Vivaldi secret key path is empty
browser.go:154: debug Vivaldi find download file failed, ERR:find History failed
browser.go:154: debug Vivaldi find password file failed, ERR:find Login Data failed
browser.go:154: debug Vivaldi find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug Vivaldi find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug Vivaldi find cookie file failed, ERR:find Cookies failed
browser.go:154: debug Vivaldi find history file failed, ERR:find History failed
cmd.go:69: error OperaGX secret key path is empty
browser.go:154: debug OperaGX find password file failed, ERR:find Login Data failed
browser.go:154: debug OperaGX find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug OperaGX find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug OperaGX find cookie file failed, ERR:find Cookies failed
browser.go:154: debug OperaGX find history file failed, ERR:find History failed
browser.go:154: debug OperaGX find download file failed, ERR:find History failed
browser.go:207: debug Firefox Dev find bookmark file failed, ERR:find places.sqlite failed
browser.go:207: debug Firefox Dev find cookie file failed, ERR:find cookies.sqlite failed
browser.go:207: debug Firefox Dev find history file failed, ERR:find places.sqlite failed
browser.go:207: debug Firefox Dev find download file failed, ERR:find places.sqlite failed
browser.go:201: debug Firefox Dev find password file failed, ERR:find logins.json failed
cmd.go:69: error Chrome Beta secret key path is empty
browser.go:154: debug Chrome Beta find cookie file failed, ERR:find Cookies failed
browser.go:154: debug Chrome Beta find history file failed, ERR:find History failed
browser.go:154: debug Chrome Beta find download file failed, ERR:find History failed
browser.go:154: debug Chrome Beta find password file failed, ERR:find Login Data failed
browser.go:154: debug Chrome Beta find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug Chrome Beta find bookmark file failed, ERR:find Bookmarks failed
browser.go:158: debug Microsoft Edge find history File Success
browser.go:158: debug Microsoft Edge find download File Success
browser.go:158: debug Microsoft Edge find password File Success
browser.go:158: debug Microsoft Edge find creditcard File Success
browser.go:154: debug Microsoft Edge find bookmark file failed, ERR:find Bookmarks failed
browser.go:158: debug Microsoft Edge find cookie File Success
[x]: Get 70 history, filename is results/microsoft_edge_history.csv
[x]: Get 0 download history, filename is results/microsoft_edge_download.csv
[x]: Get 1 passwords, filename is results/microsoft_edge_password.csv
[x]: Get 0 credit cards, filename is results/microsoft_edge_credit.csv
[x]: Get 42 cookies, filename is results/microsoft_edge_cookie.csv
browser.go:154: debug qq find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug qq find cookie file failed, ERR:find Cookies failed
browser.go:154: debug qq find history file failed, ERR:find History failed
browser.go:154: debug qq find download file failed, ERR:find History failed
browser.go:154: debug qq find password file failed, ERR:find Login Data failed
browser.go:154: debug qq find creditcard file failed, ERR:find Web Data failed
cmd.go:69: error Opera secret key path is empty
browser.go:154: debug Opera find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug Opera find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug Opera find cookie file failed, ERR:find Cookies failed
browser.go:154: debug Opera find history file failed, ERR:find History failed
browser.go:154: debug Opera find download file failed, ERR:find History failed
browser.go:154: debug Opera find password file failed, ERR:find Login Data failed
browser.go:211: debug Firefox find bookmark file success
browser.go:211: debug Firefox find cookie file success
browser.go:211: debug Firefox find history file success
browser.go:211: debug Firefox find download file success
browser.go:201: debug Firefox find password file failed, ERR:find logins.json failed
[x]: Get 5 bookmarks, filename is results/firefox_bookmark.csv
[x]: Get 38 cookies, filename is results/firefox_cookie.csv
parse.go:416: sql: Scan error on column index 2, name "last_visit_date": converting NULL to int64 is unsupported
parse.go:416: sql: Scan error on column index 2, name "last_visit_date": converting NULL to int64 is unsupported
parse.go:416: sql: Scan error on column index 2, name "last_visit_date": converting NULL to int64 is unsupported
parse.go:416: sql: Scan error on column index 2, name "last_visit_date": converting NULL to int64 is unsupported
parse.go:416: sql: Scan error on column index 2, name "last_visit_date": converting NULL to int64 is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
parse.go:416: sql: Scan error on column index 3, name "title": converting NULL to string is unsupported
[x]: Get 80 history, filename is results/firefox_history.csv
[x]: Get 3 download history, filename is results/firefox_download.csv
browser.go:207: debug Firefox Nightly find bookmark file failed, ERR:find places.sqlite failed
browser.go:207: debug Firefox Nightly find cookie file failed, ERR:find cookies.sqlite failed
browser.go:207: debug Firefox Nightly find history file failed, ERR:find places.sqlite failed
browser.go:207: debug Firefox Nightly find download file failed, ERR:find places.sqlite failed
browser.go:201: debug Firefox Nightly find password file failed, ERR:find logins.json failed
browser.go:158: debug Brave find password File Success
browser.go:158: debug Brave find creditcard File Success
browser.go:154: debug Brave find bookmark file failed, ERR:find Bookmarks failed
browser.go:158: debug Brave find cookie File Success
browser.go:158: debug Brave find history File Success
browser.go:158: debug Brave find download File Success
[x]: Get 0 passwords, filename is results/brave_password.csv
[x]: Get 0 credit cards, filename is results/brave_credit.csv
[x]: Get 344 cookies, filename is results/brave_cookie.csv
[x]: Get 34 history, filename is results/brave_history.csv
[x]: Get 0 download history, filename is results/brave_download.csv
cmd.go:69: error CocCoc secret key path is empty
browser.go:154: debug CocCoc find download file failed, ERR:find History failed
browser.go:154: debug CocCoc find password file failed, ERR:find Login Data failed
browser.go:154: debug CocCoc find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug CocCoc find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug CocCoc find cookie file failed, ERR:find Cookies failed
browser.go:154: debug CocCoc find history file failed, ERR:find History failed
browser.go:207: debug Firefox ESR find download file failed, ERR:find places.sqlite failed
browser.go:201: debug Firefox ESR find password file failed, ERR:find logins.json failed
browser.go:207: debug Firefox ESR find bookmark file failed, ERR:find places.sqlite failed
browser.go:207: debug Firefox ESR find cookie file failed, ERR:find cookies.sqlite failed
browser.go:207: debug Firefox ESR find history file failed, ERR:find places.sqlite failed
browser.go:158: debug Chrome find download File Success
browser.go:158: debug Chrome find password File Success
browser.go:158: debug Chrome find creditcard File Success
browser.go:158: debug Chrome find bookmark File Success
browser.go:154: debug Chrome find cookie file failed, ERR:find Cookies failed
browser.go:158: debug Chrome find history File Success
[x]: Get 4 download history, filename is results/chrome_download.csv
[x]: Get 5 passwords, filename is results/chrome_password.csv
[x]: Get 0 credit cards, filename is results/chrome_credit.csv
[x]: Get 4 bookmarks, filename is results/chrome_bookmark.csv
[x]: Get 136 history, filename is results/chrome_history.csv
cmd.go:69: error Yandex secret key path is empty
browser.go:154: debug Yandex find creditcard file failed, ERR:find Web Data failed
browser.go:154: debug Yandex find bookmark file failed, ERR:find Bookmarks failed
browser.go:154: debug Yandex find cookie file failed, ERR:find Cookies failed
browser.go:154: debug Yandex find history file failed, ERR:find History failed
browser.go:154: debug Yandex find download file failed, ERR:find History failed
browser.go:154: debug Yandex find password file failed, ERR:find Login Data failed

**Comment by moonD4rk** [comment]
HI, guys. I think this issuse has been solved in version[ v0.4.0](https://github.com/moonD4rk/HackBrowserData/releases), if there are still problems you can reopen.
