### ISSUE TITLE
parse.go:639 xxx : have empty password cipher: message authentication failed

### ISSUE THREAD

**Issue by je5442804** [moonD4rk/HackBrowserData#106]
# Describe the bug
I'm trying to decrypt chrome password from user: Administrator.
I am not sure why, maybe due to Administrator windows password is a blank space?
So the result will only username but not password,(result password is Blank) while other tool BrowserGhost work.
I'm sure the user chrome really have real store text password not NULL.

parse.go:639: debug http://xxx/login.html have empty password cipher: message authentication failed
parse.go:639: debug http://xxx/login.html have empty password cipher: message authentication failed
........
......
hack-browser-data--windows-64bit version 0.3.7
OS : Windows 7 (6.1 Build 7601, Service Pack 1).
Browser: Google Chrome 96.0.4664.110 (x64)

**Comment by moonD4rk** [comment]
Okey, this issue has come up before and I will try to fix it.

**Comment by moonD4rk** [comment]
fixed in version[ v0.4.0](https://github.com/moonD4rk/HackBrowserData/releases), if there are still problems you can reopen.
