### ISSUE TITLE
Question about 32 bit compile

### ISSUE THREAD

**Issue by baiyies** [moonD4rk/HackBrowserData#107]
Hello, When I build the this project use `go bulid`, it works and can extract the right data, however when I ` set GOARCH=386 `to build the 32 bit exe, I can only extract bookmark, other csv files like password and cookies are empty, and I get these output `cmd.go:88: error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub`. Could you plz tell me how to build the 32 bit exe.

**Comment by moonD4rk** [comment]
build with `CGO_ENABLED=1`
