### ISSUE TITLE
不能导出搜狗浏览器历史记录吗？以及 --key-file-path value参数是如何使用的呢？希望可以有一个更详细的参考文档

### ISSUE THREAD

**Issue by sijidufei** [moonD4rk/HackBrowserData#110]
**Describe the bug**
Use `./hack-browser-data -vv` paste result here

**Desktop (please complete the following information):**
 - OS Name: 
 - Browser Name:
 - Browser Version:

**Additional context**

**Comment by moonD4rk** [comment]
This feature will be optimized in the next release.

**Comment by moonD4rk** [comment]
don't support sugou browser.
