### ISSUE TITLE
Can't dump passwords from Chrome on MacOS

### ISSUE THREAD

**Issue by DeadNumbers** [moonD4rk/HackBrowserData#111]
**Describe the bug**
```
./hack-browser-data --vv -b chrome
cmd.go:69: error exit status 36
browser.go:154: debug Chrome find bookmark file failed, ERR:find Bookmarks failed
browser.go:158: debug Chrome find cookie File Success
browser.go:158: debug Chrome find history File Success
browser.go:158: debug Chrome find download File Success
browser.go:158: debug Chrome find password File Success
browser.go:158: debug Chrome find creditcard File Success
[x]:  Get 103 cookies, filename is results/chrome_cookie.csv 
[x]:  Get 8 history, filename is results/chrome_history.csv 
[x]:  Get 0 download history, filename is results/chrome_download.csv 
[x]:  Get 1 passwords, filename is results/chrome_password.csv 
[x]:  Get 0 credit cards, filename is results/chrome_credit.csv 
```

**Desktop (please complete the following information):**
```
Software:

    System Software Overview:

      System Version: macOS 11.6 (20G165)
      Kernel Version: Darwin 20.6.0
      Boot Volume: System
      Boot Mode: Normal
      Computer Name: MacBook Pro — Admin
      User Name: Admin (admin)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 19 minutes
```
Google Chrome `97.0.4692.99`

Password string is empty. 

```
UserName,Password,LoginUrl,CreateDate
MyName,,https://google.com/,2022-01-20T16:29:35.442975Z
```

**Comment by ryanamaral** [comment]
The password string is returned on a macOS `10.15.6 (19G2021)` with Google Chrome `97.0.4692.71`. 
Hope it helps debugging the issue.

**Comment by moonD4rk** [comment]
Hi @ryanamaral , Try use v0.4.0 to check if the bug has been fixed. If it is not fixed, you can reopen this Issuse

> **Describe the bug**
> 
> ```
> ./hack-browser-data --vv -b chrome
> cmd.go:69: error exit status 36
> browser.go:154: debug Chrome find bookmark file failed, ERR:find Bookmarks failed
> browser.go:158: debug Chrome find cookie File Success
> browser.go:158: debug Chrome find history File Success
> browser.go:158: debug Chrome find download File Success
> browser.go:158: debug Chrome find password File Success
> browser.go:158: debug Chrome find creditcard File Success
> [x]:  Get 103 cookies, filename is results/chrome_cookie.csv 
> [x]:  Get 8 history, filename is results/chrome_history.csv 
> [x]:  Get 0 download history, filename is results/chrome_download.csv 
> [x]:  Get 1 passwords, filename is results/chrome_password.csv 
> [x]:  Get 0 credit cards, filename is results/chrome_credit.csv 
> ```
> 
> **Desktop (please complete the following information):**
> 
> ```
> Software:
> 
>     System Software Overview:
> 
>       System Version: macOS 11.6 (20G165)
>       Kernel Version: Darwin 20.6.0
>       Boot Volume: System
>       Boot Mode: Normal
>       Computer Name: MacBook Pro — Admin
>       User Name: Admin (admin)
>       Secure Virtual Memory: Enabled
>       System Integrity Protection: Enabled
>       Time since boot: 19 minutes
> ```
> 
> Google Chrome `97.0.4692.99`
> 
> Password string is empty.
> 
> ```
> UserName,Password,LoginUrl,CreateDate
> MyName,,https://google.com/,2022-01-20T16:29:35.442975Z
> ```
