### ISSUE TITLE
Can cookie data be sucessfully extracted if the cookie file is copied to a different device?

### ISSUE THREAD

**Issue by squodgeface** [moonD4rk/HackBrowserData#112]
I am using the latest version under Windows 10.

I have a VirtualBox machine and I run Chrome. I login to an account, visit websites, generate cookies, etc. 

I then extract the cookies using the `-f json` option. It works great!

(I find I need to copy the `Cookies` file from the `Network` subdirectory to the `Default` directory for it to work).

Now I copy the `User Data` directory which contains all the Chrome information to a second VirtualBox machine. I replace the existing `User Data` directory with the copied `User Data` directory. I do exactly the same thing as before. However, when I run, the cookies are extracted but the problem is that the `"Value":` of every cookie is `""` (empty).

For example:
```
".doubleclick.net": [
		{
			"Host": ".doubleclick.net",
			"Path": "/",
			"KeyName": "IDE",
			"Value": "",
			"IsSecure": true,
			"IsHTTPOnly": true,
			"HasExpire": true,
			"IsPersistent": true,
			"CreateDate": "2022-01-27T10:47:45.823341Z",
			"ExpireDate": "2023-02-21T10:47:45.823341Z"
```
The very same cookie extracted in the OS where it was generated (by accessing the website) would have an actual value for `"Value":` For example:
```
".doubleclick.net": [
		{
			"Host": ".doubleclick.net",
			"Path": "/",
			"KeyName": "IDE",
			"Value": "AHWqTUlijKrU9SxcKgq7qv7UaeiwQb-nEo3WdTdzc4czMtW9foLkIkLyaHnGTuoC",
			"IsSecure": true,
			"IsHTTPOnly": true,
			"HasExpire": true,
			"IsPersistent": true,
			"CreateDate": "2022-01-27T10:47:45.823341Z",
			"ExpireDate": "2023-02-21T10:47:45.823341Z"
```

Is there a way to extract cookie values if the browser data is copied into a new operating system? Thanks.

**Comment by moonD4rk** [comment]
The OS will call the decryption method when decrypting(for windows, it's [DPAPI](https://support.microsoft.com/en-us/topic/bf374083-626f-3446-2a9d-3f6077723a60)), each OS's decryption details is different, copy the file to a new operating system and then decrypt it is not possible.
More information can be found under this ISSUE https://github.com/moonD4rk/HackBrowserData/issues/63

**Comment by squodgeface** [comment]
Thank you for the explanation. 
Can I just check one thing: is this an OS issue or is this a browser issue? I think OS. 
Would this mean that a person running Chrome on a Mac #1 wouldn't be able to extract the cookies from Mac #2?

**Comment by moonD4rk** [comment]
> Thank you for the explanation. Can I just check one thing: is this an OS issue or is this a browser issue? I think OS. Would this mean that a person running Chrome on a Mac_One wouldn't be able to extract the cookies from Mac_Two?

Yep!

**Comment by squodgeface** [comment]
So what is the purpose of this feature? Is it to prevent stealing of encrypted cookie files? 
Or is there some other reason?
