### ISSUE TITLE
Can't retrieve chrome CC

### ISSUE THREAD

**Issue by Exhaaust** [moonD4rk/HackBrowserData#114]
Use `./hack-browser-data -vv` paste result here : 

[x]:  Get 0 credit cards, filename is results/chrome_credit.csv

 - OS Name: Windows 10
 - Browser Name: Chrome
 - Browser Version:  97.0.4692.99 

Can't retrive chrome Credits Cards, while i've got 3 stored in this

Thanks in advance for the future help 👍

**Comment by MrNonoss** [comment]
Same here.

![Capture](https://user-images.githubusercontent.com/36547138/154099029-d7663ed5-f7eb-4e8d-9c06-fa8591b17ba4.PNG)

The tool detects 14 Credit Cards, but the "chrome_credits.csv" is empty.

**Comment by moonD4rk** [comment]
I think this issuse has been resoved in [v0.4.0](https://github.com/moonD4rk/HackBrowserData/releases)
