### ISSUE TITLE
[BUG]Firefox can't export bookmark's URL

### ISSUE THREAD

**Issue by ForeverHacker** [moonD4rk/HackBrowserData#118]
![图片](https://user-images.githubusercontent.com/51052851/161374322-5b7882d7-a894-468b-935e-c98f4cff1ab8.png)

**Comment by moonD4rk** [comment]
Please add more information, OS version, Firefox version…

**Comment by ForeverHacker** [comment]
FirefoxVersion：99.0.1 (64 位)
latest version

**Comment by moonD4rk** [comment]
This is a folder and will not have a URL
