### ISSUE TITLE
Get flagged by antivirus

### ISSUE THREAD

**Issue by Reversing26** [moonD4rk/HackBrowserData#132]
Like 3 or 10 days after downloading your program it get flagged by antivirus...

Are you hiding malicious content inside it?

**Comment by Reversing26** [comment]
If this program is a trojan I will blackmail you

**Comment by Reversing26** [comment]
I think you stolen my credential becouse AV said it's trojan, I will refer to cops man :)

**Comment by moonD4rk** [comment]
Read https://github.com/moonD4rk/HackBrowserData#install

**Comment by Reversing26** [comment]
All AVs on virus total keeps telling it's a trojan, I will report this repo
