### ISSUE TITLE
find browser OperaGX failed, profile folder is not exist - Even When Manually entering path

### ISSUE THREAD

**Issue by PandoricGalaxy** [moonD4rk/HackBrowserData#136]
**Describe the bug**
![image](https://user-images.githubusercontent.com/86944806/169475033-68a04fac-6f18-498e-8f4d-8a3943f36a52.png)
Auto detecting profile doesnt work nor even entering its location manually it doesnt find profile although i have passwords.db folder also there

**Desktop (please complete the following information):**
 - OS Name: Windows 10 Home
 - Browser Name: Opera GX
 - Browser Version: 85

**Comment by moonD4rk** [comment]
Try adding double quotes
```
hack-browser-data.exe -b opera-gx -p "your-profile-path"
```

**Comment by moonD4rk** [comment]
This has been fixed after v0.4.3
