### ISSUE TITLE
[BUG]Cannot get the Chrome password on Linux

### ISSUE THREAD

**Issue by codycjy** [moonD4rk/HackBrowserData#141]
**Describe the bug**
Use `./hack-browser-data -vv` paste result here

➜  ~ ./hack-browser-data-linux-amd64 -vv
[NOTICE] [browser.go:46,pickChromium] find browser Opera failed, profile folder is not exist  
[NOTICE] [browser.go:46,pickChromium] find browser Vivaldi failed, profile folder is not exist  
[NOTICE] [browser.go:46,pickChromium] find browser Brave failed, profile folder is not exist  
[INFO] [chromium.go:89,getItemPath] Chrome profile parentDir: /home/saltfish/.config/google-chrome  
[INFO] [chromium.go:90,getItemPath] Chrome profile baseDir: Default  
[NOTICE] [browser.go:50,pickChromium] find browser Chrome success  
[INFO] [chromium.go:89,getItemPath] Microsoft Edge profile parentDir: /home/saltfish/.config/microsoft-edge  
[INFO] [chromium.go:90,getItemPath] Microsoft Edge profile baseDir: Default  
[NOTICE] [browser.go:50,pickChromium] find browser Microsoft Edge success  
[INFO] [chromium.go:89,getItemPath] Chromium profile parentDir: /home/saltfish/.config/chromium  
[INFO] [chromium.go:90,getItemPath] Chromium profile baseDir: Default  
[NOTICE] [browser.go:50,pickChromium] find browser Chromium success  
[NOTICE] [browser.go:46,pickChromium] find browser Chrome Beta failed, profile folder is not exist  
[NOTICE] [browser.go:90,pickFirefox] find browser firefox firefox-nvc2gabt.default-release success  
[INFO] [chromium_linux.go:67,GetMasterKey] Chrome initialized master key success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chrome_password.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chrome_localstorage.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chrome_bookmark.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chrome_cookie.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chrome_extension.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chrome_history.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chrome_download.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chrome_creditcard.csv success  
[INFO] [chromium_linux.go:67,GetMasterKey] Microsoft Edge initialized master key success  
[NOTICE] [browsingdata.go:61,Output] output to file results/microsoft_edge_creditcard.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/microsoft_edge_localstorage.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/microsoft_edge_cookie.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/microsoft_edge_extension.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/microsoft_edge_history.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/microsoft_edge_download.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/microsoft_edge_password.csv success  
[INFO] [chromium_linux.go:67,GetMasterKey] Chromium initialized master key success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chromium_localstorage.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chromium_cookie.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chromium_extension.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chromium_history.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chromium_download.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chromium_password.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/chromium_creditcard.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/firefox_nvc2gabt_default_release_password.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/firefox_nvc2gabt_default_release_bookmark.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/firefox_nvc2gabt_default_release_history.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/firefox_nvc2gabt_default_release_download.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/firefox_nvc2gabt_default_release_localstorage.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/firefox_nvc2gabt_default_release_cookie.csv success  
[NOTICE] [browsingdata.go:61,Output] output to file results/firefox_nvc2gabt_default_release_extension.csv success 

**Desktop (please complete the following information):**
 - OS Name: 20.04.1-Ubuntu
 - Browser Name:Chrome
 - Browser Version:102.0.5005.61

**Additional context**
Cannot get real password. I got passwords like these
"¿Õ#õô5§vg
?ÔR", Ì>|[A|¢)-úKP½,

probably because the passwords are protected by system key chain.
However, the firsrt line of the result file seems correct.

**Comment by moonD4rk** [comment]
I think this BUG same as https://github.com/moonD4rk/HackBrowserData/issues/161, Chrome MasterKey not generate by default `D-Bus Keyring`, so decrypt failed. I will closed this ISSUSE first, more discussion can be found in #161
