### ISSUE TITLE
Despite I did chmod +x I have still this... It says folders not found, but they exist

### ISSUE THREAD

**Issue by guest2921** [moonD4rk/HackBrowserData#164]
./hack-browser-data
[NOTICE] [browser.go:46,pickChromium] find browser Chromium failed, profile folder does not exist  
[NOTICE] [browser.go:46,pickChromium] find browser Chrome Beta failed, profile folder does not exist  
[NOTICE] [browser.go:46,pickChromium] find browser Opera failed, profile folder does not exist  
[NOTICE] [browser.go:46,pickChromium] find browser Vivaldi failed, profile folder does not exist  
[NOTICE] [browser.go:46,pickChromium] find browser Brave failed, profile folder does not exist  
[NOTICE] [browser.go:46,pickChromium] find browser Chrome failed, profile folder does not exist  
[NOTICE] [browser.go:46,pickChromium] find browser Microsoft Edge failed, profile folder does not exist  
[NOTICE] [browser.go:90,pickFirefox] find browser firefox Firefox failed, profile folder does not exist

**Comment by guest2921** [comment]
I'm using Linux AMD64

**Comment by moonD4rk** [comment]
use `-p` flag to choose browser profile folder
```
   --profile-path value, -p value    custom profile dir path, get with chrome://version
```
