### ISSUE TITLE
Error while compiling on Kali Linux, I have GO last version GCC and musl, but I still get this output

### ISSUE THREAD

**Issue by guest2921** [moonD4rk/HackBrowserData#165]
CC=x86_64-linux-musl-gcc CXX=x86_64-linux-musl-g++ GOARCH=amd64 GOOS=linux CGO_ENABLED=1 go build -ldflags "-linkmode external -extldflags -static"
go build: when using gccgo toolchain, please pass linker flags using -gccgoflags, not -ldflags
# golang.org/x/exp/constraints
/root/go/pkg/mod/golang.org/x/exp@v0.0.0-20220414153411-bcd21879b8fd/constraints/constraints.go:13:9: error: invalid character 0x7e in input file
   13 |         ~int | ~int8 | ~int16 | ~int32 | ~int64
      |         ^
/root/go/pkg/mod/golang.org/x/exp@v0.0.0-20220414153411-bcd21879b8fd/constraints/constraints.go:20:9: error: invalid character 0x7e in input file
   20 |         ~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~uintptr
      |         ^
/root/go/pkg/mod/golang.org/x/exp@v0.0.0-20220414153411-bcd21879b8fd/constraints/constraints.go:27:9: error: expected signature or type name
   27 |         Signed | Unsigned
      |         ^
/root/go/pkg/mod/golang.org/x/exp@v0.0.0-20220414153411-bcd21879b8fd/constraints/constraints.go:34:9: error: invalid character 0x7e in input file
   34 |         ~float32 | ~float64
      |         ^
/root/go/pkg/mod/golang.org/x/exp@v0.0.0-20220414153411-bcd21879b8fd/constraints/constraints.go:41:9: error: invalid character 0x7e in input file
   41 |         ~complex64 | ~complex128
      |         ^
/root/go/pkg/mod/golang.org/x/exp@v0.0.0-20220414153411-bcd21879b8fd/constraints/constraints.go:49:9: error: expected signature or type name
   49 |         Integer | Float | ~string
      |         ^
/root/go/pkg/mod/golang.org/x/exp@v0.0.0-20220414153411-bcd21879b8fd/constraints/constraints.go:49:27: error: invalid character 0x7e in input file
   49 |         Integer | Float | ~string
      |                           ^

**Comment by moonD4rk** [comment]
Neet Go 1.18+

**Comment by guest2921** [comment]
I have Go 1.19 ... Not supported?

**Comment by moonD4rk** [comment]
> I have Go 1.19 ... Not supported?

I don't have an amd64 Linux machine, you can search Google about how to cross compiling CGO project from Linux.

https://dh1tw.de/2019/12/cross-compiling-golang-cgo-projects/
