### ISSUE TITLE
The software requires camera permission

### ISSUE THREAD

**Issue by nalanqingfeng** [moonD4rk/HackBrowserData#174]
Why does it always prompt me to get camera access when I'm using this software?

**Comment by moonD4rk** [comment]
camera? I don't think it needs "camera" permissions. 

use `./hack-browser-data -vv` on your console and print output log.

**Comment by nalanqingfeng** [comment]
I had Kaspersky on my computer, and when I opened the program Kaspersky told me it was gaining access to the camera, and then it deleted it。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月25日 17:18
收件人: ***@***.***>
抄送: Eric ***@***.***>; ***@***.***>
主题: Re: [moonD4rk/HackBrowserData] The software requires camera permission (Issue #174)


camera? I don't think it needs "camera" permissions.

use ./hack-browser-data -vv on your console and print output log.

**Comment by moonD4rk** [comment]
> I had Kaspersky on my computer, and when I opened the program Kaspersky told me it was gaining access to the camera, and then it deleted it。

It's treated as a virus by Windows Defender or some other Antivirus Software. you could trust this binary from release or build by yourself.

https://github.com/moonD4rk/HackBrowserData#install

**Comment by nalanqingfeng** [comment]
Okay, I'll try

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月25日 18:05
收件人: ***@***.***>
抄送: Eric ***@***.***>; ***@***.***>
主题: Re: [moonD4rk/HackBrowserData] The software requires camera permission (Issue #174)


I had Kaspersky on my computer, and when I opened the program Kaspersky told me it was gaining access to the camera, and then it deleted it。

It's treated as a virus by Windows Defender or some other Antivirus Software. you could trust this binary from release or build by yourself.

https://github.com/moonD4rk/HackBrowserData#install
