### ISSUE TITLE
Technical question

### ISSUE THREAD

**Issue by Reversing26** [moonD4rk/HackBrowserData#176]
Which is the function/s detected as malicious by the AV in this tool?

**Comment by moonD4rk** [comment]
Mainly [DPAPI](https://github.com/moonD4rk/HackBrowserData/blob/master/internal/decrypter/decrypter_windows.go#L75). Due to the large number of people downloading binary from Release, the Hash value has been blacklisted by various antivirus programs and browsers security check.
