### ISSUE TITLE
Package implement?

### ISSUE THREAD

**Issue by Dontmindmes** [moonD4rk/HackBrowserData#18]
Hey could you implement a package system so we can use this program in our software? chrome, err := Recovery(browser, "text.json", history,password,cookie)

**Comment by moonD4rk** [comment]
ok, I would add this feature today or tomorrow.

**Comment by Dontmindmes** [comment]
Thank you, would it be possible to make it so you can choose only windows function so build is smaller?

**Comment by moonD4rk** [comment]
@Dontmindmes compiling for windows only seems impossible!  And this tool is best used as a command-line tool.
I've added two new interface structs. The functions in these two interfaces will hopefully help you to use them in your own projects.
```golang
type Browser interface {
	InitSecretKey() error
	GetName() string
	GetSecretKey() []byte
	GetAllItems(itemName string) ([]common.Item, error)
}

type Item interface {
	ChromeParse(key []byte) error
	FirefoxParse() error
	OutPut(format, browser, dir string) error
	CopyItem() error
	Release() error
}

```
