### ISSUE TITLE
是否支持导出当前主机所有用户的密码

### ISSUE THREAD

**Issue by 0nion1** [moonD4rk/HackBrowserData#183]
是否支持导出当前主机所有用户的密码

**Comment by moonD4rk** [comment]
yep, supported all user's data from chromium based browser.

**Comment by moonD4rk** [comment]
Default enabled. 
<img width="875" alt="Screenshot 2022-12-04 at 23 06 39" src="https://user-images.githubusercontent.com/24284231/205498432-075a3fac-b497-4919-9364-1e2d3a539837.png">

**Comment by 0nion1** [comment]
Thank you very much

**Comment by moonD4rk** [comment]
Only support export other user data in browser, can't export other user's data in computer.
