### ISSUE TITLE
There is a problem with the import package

### ISSUE THREAD

**Issue by banjie123** [moonD4rk/HackBrowserData#187]
![image](https://user-images.githubusercontent.com/89896919/206896607-d982baae-3aad-4b65-8dfc-9c2ec37d147b.png)

go: finding module for package github.com/urfave/8cli/v2
hack-browser-data/cmd/hack-browser-data imports
	github.com/urfave/8cli/v2: cannot find module providing package github.com/urfave/8cli/v2: module github.com/urfave/8cli/v2: reading https://goproxy.cn/github.com/urfave/8cli/v2/@v/list: 404 Not Found
	server response:
	not found: module github.com/urfave/8cli/v2: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/56a901de6777b46948a3a0eb4dfb84b62168b6eee99ea02797c8b6405b94b9f0: exit status 128:
		fatal: could not read Username for 'https://github.com': terminal prompts disabled
	Confirm the import path was entered correctly.
	If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.

**Comment by moonD4rk** [comment]
It may be that you have modified the code. replace `github.com/urfave/8cli/v2 ` with `github.com/urfave/cli/v2`
