### ISSUE TITLE
mopen : The system cannot find the file specified

### ISSUE THREAD

**Issue by LinLuosheng** [moonD4rk/HackBrowserData#188]
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser qq_default success[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser Chrome success[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser chrome_default success[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser Chrome Beta failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser Opera failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser Yandex failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser CocCoc failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser Brave failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser 360speed success[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser 360speed_default success[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser Microsoft Edge success[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser microsoft_edge_default success[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser Chromium failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser OperaGX failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser Vivaldi failed, profile folder does not exist[0m  
[[1mNOTICE[0m] [logger.go:383,logf] [1mfind browser firefox firefox-default success[0m  
[[35mERROR[0m] [logger.go:375,log] [35mopen : The system cannot find the file specified.[0m  
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7d45ed]

goroutine 1 [running]:
hack-browser-data/internal/browingdata.(*Data).Output(0x0, {0x8b3276, 0x9}, {0x13e0c7f0, 0xa}, {0x8ab78c, 0x3})
	D:/project/go/HackBrowserData-master/internal/browingdata/browsingdata.go:51 +0x5d
main.Execute.func1(0x13c25e60)
	D:/project/go/HackBrowserData-master/cmd/hack-browser-data/main.go:58 +0x14d
github.com/urfave/cli/v2.(*Command).Run(0x13c023c0, 0x13c25e60, {0x13c0a150, 0x1, 0x1})
	C:/Users/48242/go/pkg/mod/github.com/urfave/cli/v2@v2.23.0/command.go:271 +0xa7c
github.com/urfave/cli/v2.(*App).RunContext(0x13c48a50, {0x96e7c0, 0x13c14080}, {0x13c0a150, 0x1, 0x1})
	C:/Users/48242/go/pkg/mod/github.com/urfave/cli/v2@v2.23.0/app.go:321 +0x522
github.com/urfave/cli/v2.(*App).Run(...)
	C:/Users/48242/go/pkg/mod/github.com/urfave/cli/v2@v2.23.0/app.go:298
main.Execute()
	D:/project/go/HackBrowserData-master/cmd/hack-browser-data/main.go:69 +0x6da
main.main()
	D:/project/go/HackBrowserData-master/cmd/hack-browser-data/main.go:25 +0x1a

这个报错啥意思

**Comment by moonD4rk** [comment]
This should be a Windows error and may not be related to `HackBrowserData`. For more details, please refer to this [article](https://answers.microsoft.com/en-us/windows/forum/all/the-system-cannot-find-the-file-specified-on/bb77d402-4574-47ff-b0b3-3acb5a321c15) on the Microsoft community.
