### ISSUE TITLE
[BUG] Key not valid for use in specified state.

### ISSUE THREAD

**Issue by Tardis07** [moonD4rk/HackBrowserData#189]
**Describe the bug**
[NOTICE] [logger.go:383,logf] find browser Chromium failed, profile folder does not exist
[NOTICE] [logger.go:383,logf] find browser Opera failed, profile folder does not exist
[NOTICE] [logger.go:383,logf] find browser CocCoc failed, profile folder does not exist
[NOTICE] [logger.go:383,logf] find browser QQ failed, profile folder does not exist
[NOTICE] [logger.go:383,logf] find browser Microsoft Edge success
[NOTICE] [logger.go:383,logf] find browser microsoft_edge_default success
[NOTICE] [logger.go:383,logf] find browser Sougou failed, profile folder does not exist
[NOTICE] [logger.go:383,logf] find browser Chrome success
[NOTICE] [logger.go:383,logf] find browser chrome_default success
[NOTICE] [logger.go:383,logf] find browser Chrome Beta failed, profile folder does not exist
[NOTICE] [logger.go:383,logf] find browser OperaGX failed, profile folder does not exist
[NOTICE] [logger.go:383,logf] find browser Vivaldi failed, profile folder does not exist
[NOTICE] [logger.go:383,logf] find browser Brave failed, profile folder does not exist
[NOTICE] [logger.go:383,logf] find browser Yandex failed, profile folder does not exist
[NOTICE] [logger.go:383,logf] find browser 360speed failed, profile folder does not exist
[NOTICE] [logger.go:383,logf] find browser dcbrowser failed, profile folder does not exist
[NOTICE] [logger.go:383,logf] find browser firefox firefox-p9o2twj0.default-release success
[INFO] [logger.go:383,logf] microsoft_edge_default initialized master key success
[ERROR] [logger.go:375,log] Key not valid for use in specified state.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff77ae9689b]

goroutine 1 [running]:
hack-browser-data/internal/browingdata.(*Data).Output(0xc000022d00?, {0x7ff77b0723c2, 0x7}, {0xc000010720, 0x16}, {0x7ff77b06d0d5?, 0xf77aeb7fc5?})
        C:/Users/Administrator/Desktop/HackBrowserData/internal/browingdata/browsingdata.go:51 +0x7b
main.Execute.func1(0xc000003cc0?)
        C:/Users/Administrator/Desktop/HackBrowserData/cmd/hack-browser-data/main.go:59 +0x23e
github.com/urfave/cli/v2.(*Command).Run(0xc000003cc0, 0xc000026540, {0xc0000523c0, 0x2, 0x2})
        C:/Users/Administrator/go/pkg/mod/github.com/urfave/cli/v2@v2.23.0/command.go:271 +0xaab
github.com/urfave/cli/v2.(*App).RunContext(0xc000120000, {0x7ff77b0eeca8?, 0xc00000e0d8}, {0xc0000523c0, 0x2, 0x2})
        C:/Users/Administrator/go/pkg/mod/github.com/urfave/cli/v2@v2.23.0/app.go:321 +0x658
github.com/urfave/cli/v2.(*App).Run(...)
        C:/Users/Administrator/go/pkg/mod/github.com/urfave/cli/v2@v2.23.0/app.go:298
main.Execute()
        C:/Users/Administrator/Desktop/HackBrowserData/cmd/hack-browser-data/main.go:70 +0x7d7
main.main()
        C:/Users/Administrator/Desktop/HackBrowserData/cmd/hack-browser-data/main.go:24 +0x17

**Desktop (please complete the following information):**
 - OS Name: Windows 10 22H2
 - Browser Name: Microsoft Edge
 - Browser Version: 108.0.1462.54

**Additional context**

**Comment by moonD4rk** [comment]
This should be a Windows error and may not be related to `HackBrowserData`. For more details, please refer to this [article](https://answers.microsoft.com/en-us/windows/forum/all/key-not-valid-for-use-in-specified-state/b7edbb7d-0d8c-4ac7-bfb8-93805caed4ef) on the Microsoft community.
