### ISSUE TITLE
Failed to run with custom browser profile folder

### ISSUE THREAD

**Issue by furuanruan** [moonD4rk/HackBrowserData#190]
![image](https://user-images.githubusercontent.com/90414824/209395716-102c88a1-87b1-4e8c-a8c8-c26545f5cd62.png)

hack-browser-data-windows-64bit.exe -b chrome -p 'C:\Users\Alineware\AppData\Local\Google\Chrome\User Data\Profile 1'
[FATAL] [browser.go:66,pickChromium] find browser Chrome failed, profile folder does not exist
![image](https://user-images.githubusercontent.com/90414824/209395828-74582691-9263-4efa-be46-ae909c359373.png)

**Comment by LeozinH1** [comment]
Same problem here, if you manage to solve it let me know

**Comment by cyb3rsec1990** [comment]
same problem

**Comment by moonD4rk** [comment]
Use Double quote `"` in windows CMD

```
hack-browser-data-windows-64bit.exe -b chrome -p "C:\Users\Alineware\AppData\Local\Google\Chrome\User Data\Profile 1"

```
