### ISSUE TITLE
fatal error: out of memory?

### ISSUE THREAD

**Issue by c3poo** [moonD4rk/HackBrowserData#193]
D:\>main.exe -b chrome -p "C:\Users\admin\AppData\Local\Google\Chrome\User Data\Default"
[[1mNOTICE[0m] [browser.go:73,pickChromium] [1mfind browser chrome_default success[0m  
runtime: VirtualAlloc of 567681024 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0x157d8bd?, 0xc01bc8a000?})
	/usr/local/go/src/runtime/panic.go:992 +0x76
runtime.sysUsed(0xc000580000, 0x21d62000)
	/usr/local/go/src/runtime/mem_windows.go:83 +0x1c9
runtime.(*mheap).allocSpan(0x183e580, 0x10eb1, 0x0, 0x1)
	/usr/local/go/src/runtime/mheap.go:1279 +0x428
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:912 +0x65
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:469 +0x4e

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:436 fp=0xc0003cb920 sp=0xc0003cb918 pc=0x1240b80
runtime.(*mheap).alloc(0x21d62000?, 0x10eb1?, 0x9?)
	/usr/local/go/src/runtime/mheap.go:906 +0x65 fp=0xc0003cb968 sp=0xc0003cb920 pc=0x1206c45
runtime.(*mcache).allocLarge(0x1d8bf841344f5e9?, 0x21d60001, 0x1)
	/usr/local/go/src/runtime/mcache.go:213 +0x85 fp=0xc0003cb9b8 sp=0xc0003cb968 pc=0x11f6ee5
runtime.mallocgc(0x21d60001, 0x1505040, 0x1)
	/usr/local/go/src/runtime/malloc.go:1096 +0x5a5 fp=0xc0003cba30 sp=0xc0003cb9b8 pc=0x11ed625
runtime.makeslice(0xc000006098?, 0x44?, 0x0?)
	/usr/local/go/src/runtime/slice.go:103 +0x52 fp=0xc0003cba58 sp=0xc0003cba30 pc=0x12299f2
os.ReadFile({0xc000121400?, 0x15f19a0?})
	/usr/local/go/src/os/file.go:693 +0xeb fp=0xc0003cbb38 sp=0xc0003cba58 pc=0x1286c6b
hack-browser-data/internal/utils/fileutil.CopyFile({0xc000121400?, 0x151a200?}, {0x1577932, 0x7})
	/Users/xxxskr/Downloads/HackBrowserData-0.4.4/internal/utils/fileutil/filetutil.go:99 +0x28 fp=0xc0003cbb78 sp=0xc0003cbb38 pc=0x13b25a8
hack-browser-data/internal/browser/chromium.(*chromium).copyItemToLocal(0xc000006608?)
	/Users/xxxskr/Downloads/HackBrowserData-0.4.4/internal/browser/chromium/chromium.go:83 +0x147 fp=0xc0003cbc40 sp=0xc0003cbb78 pc=0x14ab187
hack-browser-data/internal/browser/chromium.(*chromium).BrowsingData(0xc0002dfb20)
	/Users/xxxskr/Downloads/HackBrowserData-0.4.4/internal/browser/chromium/chromium.go:54 +0x92 fp=0xc0003cbc98 sp=0xc0003cbc40 pc=0x14aaf72
main.Execute.func1(0xc00019c240?)
	/Users/xxxskr/Downloads/HackBrowserData-0.4.4/cmd/hack-browser-data/main.go:58 +0x1af fp=0xc0003cbd48 sp=0xc0003cbc98 pc=0x14de0cf
github.com/urfave/cli/v2.(*App).RunContext(0xc000145380, {0x15f44c8?, 0xc00011a098}, {0xc00014a000, 0x5, 0x8})
	/Users/xxxskr/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:322 +0x953 fp=0xc0003cbed8 sp=0xc0003cbd48 pc=0x14c9993
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/xxxskr/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224
main.Execute()
	/Users/xxxskr/Downloads/HackBrowserData-0.4.4/cmd/hack-browser-data/main.go:73 +0x785 fp=0xc0003cbf70 sp=0xc0003cbed8 pc=0x14de925
main.main()
	/Users/xxxskr/Downloads/HackBrowserData-0.4.4/cmd/hack-browser-data/main.go:24 +0x17 fp=0xc0003cbf80 sp=0xc0003cbf70 pc=0x14ddef7
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x1fe fp=0xc0003cbfe0 sp=0xc0003cbf80 pc=0x1218b9e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0003cbfe8 sp=0xc0003cbfe0 pc=0x1242ee1

**Comment by moonD4rk** [comment]
Tt seems that the memory used by the program exceeds the machine's memory, which is why this error occurred. Later on, I will consider refactoring this project using Rust https://github.com/moonD4rk/HackBrowserData/discussions/201 and temporarily close this issue.

https://github.com/golang/go/issues/33716
