### ISSUE TITLE
Send the CSV file to Gmail or ....

### ISSUE THREAD

**Issue by jamiekarvans** [moonD4rk/HackBrowserData#207]
It would be really nice and usefull if the script could send the saved passwords file to Gmail or another service to be accessed later and saved there.

**Comment by moonD4rk** [comment]
https://github.com/moonD4rk/HackBrowserData/issues/46#issuecomment-731638250

> I don't think it's a good idea to add the feature to send an email. The core of this software is for decryption and forensics. It already provides compressed results to .zip (-cc). if you really need this, you can implement the feature yourself to send the zip via email or some other methods.
