### ISSUE TITLE
chrome( 84.0.4147.89)无法获取密码

### ISSUE THREAD

**Issue by FunnyWolf** [moonD4rk/HackBrowserData#21]
**Describe the bug**
chrome无法获取密码

**Screenshots**
None
**Desktop (please complete the following information):**
 - OS: windows10
 - Browser:chrome
 - Browser Version: 84.0.4147.89
 - Browser Profile Path:  [ chrome `chrome://version` firefox `about:profiles `]

**Additional context**

**Comment by moonD4rk** [comment]
Thx for your report, I'll fix this bug as soon as I can.

**Comment by moonD4rk** [comment]
@FunnyWolf Fixed, please check if this is correct. https://github.com/moonD4rk/HackBrowserData/releases/tag/v0.1.8
