### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by invoke888** [moonD4rk/HackBrowserData#214]
[ERROR] [main.go:55,func1] open : The system cannot find the file specified.  
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xc2bc1b]

goroutine 1 [running]:
github.com/moond4rk/HackBrowserData/browingdata.(*Data).Output(0xc000020a90?, {0xdb2911, 0x7}, {0xc0001ecad0, 0x10}, {0xdad5bd?, 0xadd045?})
	D:/go/HackBrowserData/browingdata/browsingdata.go:52 +0x7b
main.Execute.func1(0xc0001dc160?)
	D:/go/HackBrowserData/cmd/hack-browser-data/main.go:57 +0x24a
github.com/urfave/cli/v2.(*Command).Run(0xc0001dc160, 0xc000092580, {0xc00007e200, 0x1, 0x1})
	D:/go/GOPATH/pkg/mod/github.com/urfave/cli/v2@v2.25.0/command.go:273 +0xa42
github.com/urfave/cli/v2.(*App).RunContext(0xc0001da000, {0xe30808?, 0xc00000e0c0}, {0xc00007e200, 0x1, 0x1})
	D:/go/GOPATH/pkg/mod/github.com/urfave/cli/v2@v2.25.0/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
	D:/go/GOPATH/pkg/mod/github.com/urfave/cli/v2@v2.25.0/app.go:309
main.Execute()
	D:/go/HackBrowserData/cmd/hack-browser-data/main.go:69 +0x8b7
main.main()
	D:/go/HackBrowserData/cmd/hack-browser-data/main.go:24 +0x17

**Comment by EricZhou05** [comment]
Me too~Unable to Access Complete Data.
![屏幕截图 2023-04-09 144517](https://user-images.githubusercontent.com/61287015/230758638-95967cd5-009c-4903-8446-6d8251940348.png)

**Describe the bug**
.\hack-browser-data-windows-64bit.exe -b all -f json --dir results -zip

[NOTICE] [browser.go:47,pickChromium] find browser Vivaldi failed, profile folder does not exist
[NOTICE] [browser.go:47,pickChromium] find browser CocCoc failed, profile folder does not exist
[NOTICE] [browser.go:47,pickChromium] find browser Yandex failed, profile folder does not exist
[NOTICE] [browser.go:51,pickChromium] find browser QQ success
[NOTICE] [browser.go:51,pickChromium] find browser Microsoft Edge success
[NOTICE] [browser.go:53,pickChromium] find browser microsoft_edge_default success
[NOTICE] [browser.go:47,pickChromium] find browser Chromium failed, profile folder does not exist
[NOTICE] [browser.go:47,pickChromium] find browser Opera failed, profile folder does not exist
[NOTICE] [browser.go:47,pickChromium] find browser Brave failed, profile folder does not exist
[NOTICE] [browser.go:47,pickChromium] find browser 360speed failed, profile folder does not exist
[NOTICE] [browser.go:51,pickChromium] find browser Chrome success
[NOTICE] [browser.go:53,pickChromium] find browser chrome_default success
[NOTICE] [browser.go:47,pickChromium] find browser Chrome Beta failed, profile folder does not exist
[NOTICE] [browser.go:47,pickChromium] find browser OperaGX failed, profile folder does not exist
[NOTICE] [browser.go:91,pickFirefox] find browser firefox Firefox failed, profile folder does not exist
[ERROR] [main.go:60,func1] Key not valid for use in specified state.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x110837b]

goroutine 1 [running]:
hack-browser-data/internal/browingdata.(*Data).Output(0xc0002bccb0?, {0xc0000a00c0, 0x7}, {0xc000284198, 0x16}, {0xc0000a00a0?, 0x0?})
        /source/internal/browingdata/browsingdata.go:51 +0x7b
main.Execute.func1(0xc00011e240?)
        /source/cmd/hack-browser-data/main.go:62 +0x23e
github.com/urfave/cli/v2.(*App).RunContext(0xc000085040, {0x137bf48?, 0xc0000a00d8}, {0xc0000d0000, 0x8, 0x8})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:322 +0x97c
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224
main.Execute()
        /source/cmd/hack-browser-data/main.go:73 +0x7f6
main.main()
        /source/cmd/hack-browser-data/main.go:24 +0x17

**Desktop (please complete the following information):**

- OS Name: Win11 (Version 21H2 / DirectX 12)\
- Browser Name: Google Chrome
- Browser Version: 109.0.5414.120 64 Bits

**Comment by moonD4rk** [comment]
Duplicate with https://github.com/moonD4rk/HackBrowserData/issues/41 https://github.com/moonD4rk/HackBrowserData/issues/214

Detail in this Replay https://github.com/moonD4rk/HackBrowserData/issues/188#issuecomment-1465168108
