### ISSUE TITLE
Macos export error

### ISSUE THREAD

**Issue by sdfbjaksff** [moonD4rk/HackBrowserData#221]
**Describe the bug**
Use `./hack-browser-data -vv` paste result here

[ERROR] [main.go:60,func1] exit status 44  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42d28bb]

goroutine 1 [running]:
hack-browser-data/internal/browingdata.(*Data).Output(0xc000144000?, {0x208b86d5e, 0x7}, {0xc000331210, 0xe}, {0x208b86d53?, 0x0?})
        /source/internal/browingdata/browsingdata.go:51 +0x7b
main.Execute.func1(0xc0001ba0c0?)
        /source/cmd/hack-browser-data/main.go:62 +0x23e
github.com/urfave/cli/v2.(*App).RunContext(0xc0001031e0, {0x4549fa8?, 0xc000124010}, {0xc000128000, 0x8, 0x8})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:322 +0x97c
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224
main.Execute()
        /source/cmd/hack-browser-data/main.go:73 +0x7f6
main.main()
        /source/cmd/hack-browser-data/main.go:24 +0x17

**Desktop (please complete the following information):**
 - OS Name: MacBook-Pro
 - Browser Name:Chrome
 - Browser Version:Latest

**Additional context**
Chrome exports passwords without plaintext

**Comment by moonD4rk** [comment]
Fixed in [v0.4.6](https://github.com/moonD4rk/HackBrowserData/releases)
