### ISSUE TITLE
process cannot access the file because it is being used by another process.  

### ISSUE THREAD

**Issue by doge-dog** [moonD4rk/HackBrowserData#233]
[ERROR] [main.go:55,func1] open : The system cannot find the file specified.  
[ERROR] [main.go:55,func1] open C:\Users\Administrator\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies: The process cannot access the file because it is being used by another process.  
[NOTICE] [browsingdata.go:72,Output] output to file results/chrome_def_sessionstorage.csv success  
[ERROR] [main.go:55,func1] open : The system cannot find the file specified.  
[NOTICE] [browsingdata.go:72,Output] output to file results/firefox_default_bookmark.csv success  
[NOTICE] [browsingdata.go:72,Output] output to file results/firefox_default_history.csv success

**Comment by doge-dog** [comment]
原因：由于新版本chrome对cookies文件做了lock操作，导致读取失败

**Comment by doge-dog** [comment]
通过创建卷影成功提取Cookies文件，可参考写成自动化

**Comment by 23jdn** [comment]
> 通过创建卷影成功提取Cookies文件，可参考写成自动化

如何进行卷影复制，有相关文章链接吗? 类似与对该文件创建快照吗

**Comment by doge-dog** [comment]
> > 通过创建卷影成功提取Cookies文件，可参考写成自动化
> 
> 如何进行卷影复制，有相关文章链接吗? 类似与对该文件创建快照吗

跟操作ntds一样的原理，做个快照把文件拷出来解析

**Comment by doge-dog** [comment]
已找到平替方法，通过rawcopy一样可以实现cookies文件的copy，https://github.com/kmahyyg/go-rawcopy

**Comment by moonD4rk** [comment]
Discuss the specific solution to this issue in this ISSUSE. 👇↳

https://github.com/moonD4rk/HackBrowserData/issues/243
