### ISSUE TITLE
How do I import chrome?

### ISSUE THREAD

**Issue by ikoiko12** [moonD4rk/HackBrowserData#25]
How do I import chrome?

**Comment by moonD4rk** [comment]
Import chrome? I don't know what exactly you mean. can you tell me more information?

**Comment by ikoiko12** [comment]
When I export a chrome_cookie.json file, how do I import a chrome_cookie.json file into a chrome to enter the full data?

**Comment by moonD4rk** [comment]
`hack-browser-data` only supports export cookies, can't import cookies to the browser.
