### ISSUE TITLE
担心这个软件会不会带来安全威胁……

### ISSUE THREAD

**Issue by JerryHan3** [moonD4rk/HackBrowserData#28]
如题，如果有不法分子为这个工具加上自启动代码、自动向指定服务器发送导出的文件的代码，那么成了一个窃取密码的病毒……😱
个人的想法是把源代码闭源

**Comment by fate93930** [comment]
> 如题，如果有不法分子为这个工具加上自启动代码、自动向指定服务器发送导出的文件的代码，那么成了一个窃取密码的病毒……😱
> 个人的想法是把源代码闭源

你是傻逼吗

**Comment by moonD4rk** [comment]
**已删除人生攻击言论**
开发此软件的目的是为了在**有授权**的渗透测试中获取更多有用信息，方便下一步测试。

请勿在**无授权情况**下，在他人电脑上随意使用。
