### ISSUE TITLE
[FEATURE REQUEST] Brave Browser

### ISSUE THREAD

**Issue by xaitax** [moonD4rk/HackBrowserData#31]
Hi, 

would be great if you could also add brave browser [1] which is becoming increasingly popular. It is based on Firefox so potentially the decryptionextraction is the same.

[1] https://brave.com/download/

P.S.: Awesome tool, thank you.

**Comment by moonD4rk** [comment]
Thanks for the information, I will try to support this browser.

**Comment by moonD4rk** [comment]
It's already supported across all platforms and you can download from [Release](https://github.com/moonD4rk/HackBrowserData/releases).

Also, Brave is based on `chromium`, you can type `brave://version/` in your brave browser address bar to get more info.

**Comment by xaitax** [comment]
I meant to write Chromium. 🙈

And thanks for the implementation! 🎉
