### ISSUE TITLE
[FEATURE REQUEST]Sogou Explorer

### ISSUE THREAD

**Issue by huobaolajiao** [moonD4rk/HackBrowserData#34]
搜狗浏览器Sogou Explorer，同样的chromium内核是否存在同样的问题，是不行还是待开发？谢谢！

**Comment by moonD4rk** [comment]
搜狗浏览器虽然是基于 `Chromium`，但对其源码和对应接口进行大量修改，目前暂时没有很好的办法获取到密码等关键数据。

**Comment by huobaolajiao** [comment]
暂时放心了哈哈哈哈哈哈哈哈哈哈，魔改浏览器，当年还是一代传奇，以后再看吧
