### ISSUE TITLE
undefined: sqlite3_index_constraint

### ISSUE THREAD

**Issue by iamasbcx** [moonD4rk/HackBrowserData#343]
## Describe the bug

win32     

SET CGO_ENABLED=1
SET GOOS=windows
SET GOARCH=386
go build

# modernc.org/sqlite/lib
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:13:35: undefined: sqlite3_index_constraint
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:14:35: undefined: sqlite3_index_orderby
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:15:35: undefined: sqlite3_index_constraint_usage
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:19:5: undefined: Xsqlite3_threadsafe
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:11: undefined: Xsqlite3_config
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:32: undefined: SQLITE_CONFIG_MUTEX
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:122: undefined: SQLITE_OK
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:30:8: undefined: Xsqlite3_errstr
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:40:17: undefined: Sqlite3_mutex_methods
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:239:46: undefined: SQLITE_OK
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:239:46: too many errors

- OS Version: [e.g. windows 10
- OS Architecture: [e.g. 32-bit, 

how todo

**Comment by moonD4rk** [comment]
In the latest version of the main branch, there is no longer a need to use CGO_ENABLED =1 for compilation. Just use `go build` directly.

Sorry, the Readme has not been updated.

**Comment by iamasbcx** [comment]
new Windows 10    
go1.22.4.windows-386.msi
i686-8.1.0-release-win32-sjlj-rt_v6-rev0.7z


go build
# modernc.org/sqlite/lib
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:13:35: undefined: sqlite3_index_constraint
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:14:35: undefined: sqlite3_index_orderby
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:15:35: undefined: sqlite3_index_constraint_usage
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:19:5: undefined: Xsqlite3_threadsafe
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:11: undefined: Xsqlite3_config
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:32: undefined: SQLITE_CONFIG_MUTEX
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:122: undefined: SQLITE_OK
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:30:8: undefined: Xsqlite3_errstr
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:40:17: undefined: Sqlite3_mutex_methods
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:239:46: undefined: SQLITE_OK
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:239:46: too many errors

X86 still has the same problem

**Comment by iamasbcx** [comment]
> 在主分支的最新版本中，不再需要使用 CGO_ENABLED =1 进行编译。直接使用即可`go build`。
> 
> 抱歉，自述文件尚未更新。

新虚拟机安装 
go1.22.4.windows-386.msi
i686-8.1.0-release-win32-sjlj-rt_v6-rev0.7z

go build  问题依旧      X64没问题 直接编译通过 奇怪了 我什么都没改

**Comment by iamasbcx** [comment]
Microsoft Windows [版本 10.0.19045.3208]
(c) Microsoft Corporation。保留所有权利。

C:\Users\cx\Desktop\HackBrowserData-main\cmd\hack-browser-data>go env -w GOPROXY=https://goproxy.cn,direct

C:\Users\cx\Desktop\HackBrowserData-main\cmd\hack-browser-data>go build
go: downloading github.com/urfave/cli/v2 v2.27.1
go: downloading github.com/otiai10/copy v1.14.0
go: downloading github.com/tidwall/gjson v1.17.1
go: downloading modernc.org/sqlite v1.29.6
go: downloading github.com/gocarina/gocsv v0.0.0-20231116093920-b87c2d0e983a
go: downloading golang.org/x/text v0.14.0
go: downloading github.com/syndtr/goleveldb v1.0.0
go: downloading github.com/tidwall/match v1.1.1
go: downloading github.com/tidwall/pretty v1.2.0
go: downloading golang.org/x/sync v0.3.0
go: downloading github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading github.com/xrash/smetrics v0.0.0-20201216005158-039620a65673
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading modernc.org/libc v1.41.0
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading modernc.org/mathutil v1.6.0
go: downloading modernc.org/memory v1.7.2
go: downloading github.com/ncruces/go-strftime v0.1.9
go: downloading github.com/dustin/go-humanize v1.0.1
go: downloading github.com/remyoudompheng/bigfft v0.0.0-20230129092748-24d4a6f8daec
# modernc.org/sqlite/lib
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:13:35: undefined: sqlite3_index_constraint
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:14:35: undefined: sqlite3_index_orderby
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:15:35: undefined: sqlite3_index_constraint_usage
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:19:5: undefined: Xsqlite3_threadsafe
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:11: undefined: Xsqlite3_config
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:32: undefined: SQLITE_CONFIG_MUTEX
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:122: undefined: SQLITE_OK
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:30:8: undefined: Xsqlite3_errstr
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:40:17: undefined: Sqlite3_mutex_methods
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:239:46: undefined: SQLITE_OK
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:239:46: too many errors

C:\Users\cx\Desktop\HackBrowserData-main\cmd\hack-browser-data>

**Comment by moonD4rk** [comment]
@iamasbcx  Can you print Golang environment info via `go env` command?

**Comment by moonD4rk** [comment]
> new Windows 10 go1.22.4.windows-386.msi i686-8.1.0-release-win32-sjlj-rt_v6-rev0.7z

I think you may have installed the wrong version of Golang. Here is a list on how to install 32/64-bit Go binary files.
The Windows architecture for 386 is quite old and may not be what you need to install on a modern computer.


| Target Architecture | Go Version Architecture | Description                       | Example Download Link       |
| ------------------- | ----------------------- | --------------------------------- | --------------------------- |
| 32-bit Windows      | 386                     | For compiling 32-bit x86 programs | go1.22.4.windows-386.msi  |
| 64-bit Windows      | amd64                   | For compiling 64-bit x86 programs | go1.22.4. windows-amd64.msi |
| 64-bit Windows      | arm64                   | For compiling 64-bit ARM programs | go1.22.4. windows-arm64.msi |

Golang Support cross-compile for different OS and Arch, you don't need install target Go version. here's a example to build 32/64 bit windows binaray in Windows Console.

```shell
set GOARCH=386
set GOOS=windows
go build -o hack-browser-data-32bit.exe
```

```shell
set GOARCH=amd64
set GOOS=windows
go build -o hack-browser-data-64bit.exe
```

**Comment by iamasbcx** [comment]
Microsoft Windows [版本 10.0.19045.3208]
(c) Microsoft Corporation。保留所有权利。

C:\Users\cx\Desktop\HackBrowserData-master2024\HackBrowserData-main\cmd\hack-browser-data>set GOARCH=386

C:\Users\cx\Desktop\HackBrowserData-master2024\HackBrowserData-main\cmd\hack-browser-data>set GOOS=windows

C:\Users\cx\Desktop\HackBrowserData-master2024\HackBrowserData-main\cmd\hack-browser-data>go build -o hack-browser-data-32bit.exe
# modernc.org/sqlite/lib
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:13:35: undefined: sqlite3_index_constraint
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:14:35: undefined: sqlite3_index_orderby
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:15:35: undefined: sqlite3_index_constraint_usage
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:19:5: undefined: Xsqlite3_threadsafe
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:11: undefined: Xsqlite3_config
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:32: undefined: SQLITE_CONFIG_MUTEX
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:122: undefined: SQLITE_OK
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:30:8: undefined: Xsqlite3_errstr
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:40:17: undefined: Sqlite3_mutex_methods
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:239:46: undefined: SQLITE_OK
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:239:46: too many errors

C:\Users\cx\Desktop\HackBrowserData-master2024\HackBrowserData-main\cmd\hack-browser-data>go env
set GO111MODULE=
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\cx\AppData\Local\go-build
set GOENV=C:\Users\cx\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\cx\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\cx\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.4
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\cx\Desktop\HackBrowserData-master2024\HackBrowserData-main\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\cx\AppData\Local\Temp\go-build3283847996=/tmp/go-build -gno-record-gcc-switches

C:\Users\cx\Desktop\HackBrowserData-master2024\HackBrowserData-main\cmd\hack-browser-data>




X64 os  win10 go1.22.4.windows-amd64.msi

**Comment by iamasbcx** [comment]
Microsoft Windows [版本 10.0.19045.3208]
(c) Microsoft Corporation。保留所有权利。

C:\Users\cx\Desktop\HackBrowserData-master2024\HackBrowserData-main\cmd\hack-browser-data>go env -w GOPROXY=https://goproxy.cn,direct

C:\Users\cx\Desktop\HackBrowserData-master2024\HackBrowserData-main\cmd\hack-browser-data>set GOARCH=386

C:\Users\cx\Desktop\HackBrowserData-master2024\HackBrowserData-main\cmd\hack-browser-data>set GOOS=windows

C:\Users\cx\Desktop\HackBrowserData-master2024\HackBrowserData-main\cmd\hack-browser-data>go build -o hack-browser-data-32bit.exe
go: downloading github.com/urfave/cli/v2 v2.27.1
go: downloading github.com/otiai10/copy v1.14.0
go: downloading github.com/tidwall/gjson v1.17.1
go: downloading modernc.org/sqlite v1.29.6
go: downloading github.com/gocarina/gocsv v0.0.0-20231116093920-b87c2d0e983a
go: downloading golang.org/x/text v0.14.0
go: downloading github.com/syndtr/goleveldb v1.0.0
go: downloading github.com/tidwall/match v1.1.1
go: downloading github.com/tidwall/pretty v1.2.0
go: downloading golang.org/x/sync v0.3.0
go: downloading github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading github.com/xrash/smetrics v0.0.0-20201216005158-039620a65673
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading modernc.org/libc v1.41.0
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading github.com/dustin/go-humanize v1.0.1
go: downloading github.com/ncruces/go-strftime v0.1.9
go: downloading modernc.org/mathutil v1.6.0
go: downloading modernc.org/memory v1.7.2
go: downloading github.com/remyoudompheng/bigfft v0.0.0-20230129092748-24d4a6f8daec
# modernc.org/sqlite/lib
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:13:35: undefined: sqlite3_index_constraint
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:14:35: undefined: sqlite3_index_orderby
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\defs.go:15:35: undefined: sqlite3_index_constraint_usage
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:19:5: undefined: Xsqlite3_threadsafe
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:11: undefined: Xsqlite3_config
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:32: undefined: SQLITE_CONFIG_MUTEX
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:29:122: undefined: SQLITE_OK
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:30:8: undefined: Xsqlite3_errstr
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:40:17: undefined: Sqlite3_mutex_methods
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:239:46: undefined: SQLITE_OK
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.29.6\lib\mutex.go:239:46: too many errors

C:\Users\cx\Desktop\HackBrowserData-master2024\HackBrowserData-main\cmd\hack-browser-data>go env
set GO111MODULE=
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\cx\AppData\Local\go-build
set GOENV=C:\Users\cx\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\cx\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\cx\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files (x86)\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files (x86)\Go\pkg\tool\windows_386
set GOVCS=
set GOVERSION=go1.22.4
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\cx\Desktop\HackBrowserData-master2024\HackBrowserData-main\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\cx\AppData\Local\Temp\go-build2182372341=/tmp/go-build -gno-record-gcc-switches

C:\Users\cx\Desktop\HackBrowserData-master2024\HackBrowserData-main\cmd\hack-browser-data>


X64操作系统win10 go1.22.4.windows-386.msi

**Comment by iamasbcx** [comment]
go x64  +minwg32  OK

**Comment by moonD4rk** [comment]
Ref: https://github.com/flipped-aurora/gin-vue-admin/issues/1510

Seems this is a common error.
