### ISSUE TITLE
失败,检测到病毒

### ISSUE THREAD

**Issue by usernameisnull** [moonD4rk/HackBrowserData#35]
下载windows的编译好的包的时候,win10给出警告

**Comment by YooungJune** [comment]
添加到信任程序试试？

**Comment by moonD4rk** [comment]
可选择忽略或者将其添加到白名单。

由于这款安全工具执行过程中调用了 win32 API，被 windows defender 当作了病毒软件，我会在 0.26 版本提供了简单的绕过方法，后续不再提供被查杀后的绕过策略。

核心代码已开源，可以自己修改并编译。
