### ISSUE TITLE
"modernc.org/sqlite" does not support 32-bit Windows. What to do

### ISSUE THREAD

**Issue by iamasbcx** [moonD4rk/HackBrowserData#365]
"modernc.org/sqlite" does not support 32-bit Windows. What to do

# modernc.org/sqlite/lib
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\defs.go:13:35: undefined: sqlite3_index_constraint
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\defs.go:14:35: undefined: sqlite3_index_orderby
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\defs.go:15:35: undefined: sqlite3_index_constraint_usage
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:19:5: undefined: Xsqlite3_threadsafe
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:29:11: undefined: Xsqlite3_config
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:29:32: undefined: SQLITE_CONFIG_MUTEX
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:29:122: undefined: SQLITE_OK
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:30:8: undefined: Xsqlite3_errstr
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:40:17: undefined: Sqlite3_mutex_methods
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:239:46: undefined: SQLITE_OK
C:\Users\cx\go\pkg\mod\modernc.org\sqlite@v1.30.1\lib\mutex.go:239:46: too many errors

**Comment by moonD4rk** [comment]
modernc.org/sqlite does not support cross-platform compilation for Windows 32-bit. You need to install Go on a Windows 32-bit machine and compile without cross compile.


Here's combinations of GOOS and GOARCH are currently supported

```
OS      Arch    SQLite version
------------------------------
darwin	amd64   3.46.0
darwin	arm64   3.46.0
freebsd	amd64   3.46.0
freebsd	arm64   3.46.0
linux	386     3.46.0
linux	amd64   3.46.0
linux	arm     3.46.0
linux	arm64   3.46.0
linux	loong64 3.46.0
linux	ppc64le 3.46.0
linux	riscv64 3.46.0
linux	s390x   3.46.0
windows	amd64   3.46.0
windows	arm64   3.46.0
```
