### ISSUE TITLE
Compressed output bug

### ISSUE THREAD

**Issue by NickYan7** [moonD4rk/HackBrowserData#366]
## Describe the bug
my command (using v0.4.6):
`PS c:\> & .\hackbrowserdata.exe -f json --zip --dir $env:temp\mylogs`

It can not output the exactly zip file, seems like a bug while handling the `--dir` argument:
![image](https://github.com/user-attachments/assets/57be8992-39ac-4505-b9b5-92df10c85a6d)

eithor or the whole path, such as `C:\Users\username\AppData\Local\Temp\1\mylogs`.

## Desktop 
Win10 Pro 22H2 19045.2846

I've tested v0.4.6 && v0.4.5, all the same bug while you set a abs path.

**Comment by NickYan7** [comment]
After editing this, it can work properly.
`HackBrowserData/utils/fileutil/filetutil.go`
![image](https://github.com/user-attachments/assets/9653761d-a003-4779-92da-84a3bff79982)

Noted: I set my own zip file name.

**Comment by moonD4rk** [comment]
@NickYan7  You have passed environment variables `$env:` on the command line, `CompressDir` function does not include the functionality to parse env flag. 

Try not passing in fields related to environment variables.

**Comment by NickYan7** [comment]
> @NickYan7 You have passed environment variables `$env:` on the command line, `CompressDir` function does not include the functionality to parse env flag.
> 
> Try not passing in fields related to environment variables.

Actually the `$env:temp` is parsed by PowerShell, it returns an string then pass to `hackbrowserdata.exe`, the exactly bug is at `HackBrowserData/utils/fileutil/filetutil.go`, which I quote in the pic above.

Otherwise you can test by yourself with command `.\hackbrowserdata.exe -f json --zip --dir c:\a\abs\path`

👀

**Comment by moonD4rk** [comment]
I think this bug has been fixed.

https://github.com/moonD4rk/HackBrowserData/blob/271e0524817dfcc67415d19202288172f6264208/utils/fileutil/filetutil.go#L119
