### ISSUE TITLE
[Bug] The new version of Golang(1.21+) cannot run on Windows 7. - immediate crash

### ISSUE THREAD

**Issue by greenozon** [moonD4rk/HackBrowserData#378]
## Describe the bug
downloaded latest up-to-date archive, unpacked and run it in cmd.exe console 
just to be on the same page: SHA1 for the binary
838839f163f8cb146ef9078956fe9a733d096299 *hack-browser-data.exe

## Log Output
```
c:\Dev\>hack-browser-data.exe -vv
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x22fcf8)
        runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x47173a
rax     0x0
rbx     0xd2dff8
rcx     0xdb4be8
rdx     0x20
rdi     0x7fffffdc000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x262a2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0xd2d060
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
```

## Expected vs Actual Behavior
it works!
no any crash exception printed out...

## Desktop (please complete the following information):
Select the operating system(s) you are using:
- [x] Windows
- [ ] macOS
- [ ] Linux

- OS Version: [Windows 7 SP1 all updates installed]
- OS Architecture: [64-bit]

## Additional Details
- [x] I ran `hack-browser-data` with administrator/root privileges.
same crash as above

## Checklist
- [ x] I have checked the [existing issues](https://github.com/moonD4rk/HackBrowserData/issues) for similar problems.

## Screenshots/Videos
not sure if it's needed... all info printed out provided above

## Additional context
wanted to read my chrome 109 data, but... still can't approach it :)

**Comment by greenozon** [comment]
I did not find any pre-requisites thus come to conclusion you support majority of Windows OSes?

**Comment by moonD4rk** [comment]
@greenozon It seems that the higher versions of golang do not support the Windows 7 platform under certain conditions.
https://github.com/golang/go/issues/64622

**Comment by greenozon** [comment]
OK, got it, but it least its very weird to not print - hey, I can't run but hardly crash on a very start...
do you have control to print such message and thus make upcoming issues non-existent :)

**Comment by moonD4rk** [comment]
@greenozon  It looks like a very tricky problem, you can test if this repository is useful for you.

https://github.com/stunndard/golangwin7patch

**Comment by greenozon** [comment]
WOW God yes!
it worked like a charm (just a 3 bytes were changed in your release binary)
shockingly weird!!!

![image](https://github.com/user-attachments/assets/16ae1415-5d50-40da-a85b-4bf4ed627ec6)


Feel free to close it

Hope all future Windows 7 users will find this topic helpful as well!
