### ISSUE TITLE
[FEATURE REQUEST] extract from another mounter volume

### ISSUE THREAD

**Issue by MrNonoss** [moonD4rk/HackBrowserData#40]
Amazing tool, thanks a lot.

As a digital forensic person, I would like to ask for the possibility to extract data from another mounted volume, containing another system. 

Would it be possible to choose the source of the data ?

**Comment by moonD4rk** [comment]
It's a good idea, will support custom browser path in the future!

**Comment by moonD4rk** [comment]
@MrNonoss @joneyue version 0.3.1 support custom browser profile path, can get details here https://github.com/moonD4rk/HackBrowserData#run-with-custom-browser-profile-path

**Comment by MrNonoss** [comment]
> @MrNonoss @joneyue version 0.3.1 support custom browser profile path, can get details here https://github.com/moonD4rk/HackBrowserData#run-with-custom-browser-profile-path

Very useful improvement. Many Thanks 👍
