### ISSUE TITLE
无法正常提取qq浏览器的password和书签内容，360浏览器的数据提取完全无法工作

### ISSUE THREAD

**Issue by KJZH001** [moonD4rk/HackBrowserData#41]
**Describe the bug**

无法正常提取qq浏览器的password和书签内容

错误返回
```
browser.go:132: debug qq find bookmark File Success
browser.go:132: debug qq find cookie File Success
browser.go:132: debug qq find history File Success
browser.go:132: debug qq find password File Success
[x]:  Get 20 bookmarks, filename is results/qq_bookmark.csv
[x]:  Get 1318 cookies, filename is results/qq_cookie.csv
[x]:  Get 7440 history, filename is results/qq_history.csv
[x]:  Get 0 passwords, filename is results/qq_password.csv
browser.go:181: error Firefox find bookmark file failed, ERR:find places.sqlite
failed
browser.go:181: error Firefox find cookie file failed, ERR:find cookies.sqlite f
ailed
browser.go:181: error Firefox find history file failed, ERR:find places.sqlite f
ailed
browser.go:175: error Firefox find password file failed, ERR:find logins.json fa
iled
cmd.go:53: error open C:\Users\Administrator/AppData/Local/BraveSoftware/Brave-B
rowser/User Data/Local State: The system cannot find the path specified.
browser.go:128: error Brave find cookie file failed, ERR:find Cookies failed
browser.go:128: error Brave find history file failed, ERR:find History failed
browser.go:128: error Brave find password file failed, ERR:find Login Data faile
d
browser.go:128: error Brave find bookmark file failed, ERR:find Bookmarks failed

browser.go:132: debug Chrome find cookie File Success
browser.go:132: debug Chrome find history File Success
browser.go:132: debug Chrome find password File Success
browser.go:132: debug Chrome find bookmark File Success
[x]:  Get 76 cookies, filename is results/chrome_cookie.csv
[x]:  Get 237 history, filename is results/chrome_history.csv
[x]:  Get 6 passwords, filename is results/chrome_password.csv
[x]:  Get 8 bookmarks, filename is results/chrome_bookmark.csv
cmd.go:53: error open C:\Users\Administrator/AppData/Local/Microsoft/Edge/User D
ata/Local State: The system cannot find the path specified.
browser.go:128: error Microsoft Edge find history file failed, ERR:find History
failed
browser.go:128: error Microsoft Edge find password file failed, ERR:find Login D
ata failed
browser.go:128: error Microsoft Edge find bookmark file failed, ERR:find Bookmar
ks failed
browser.go:128: error Microsoft Edge find cookie file failed, ERR:find Cookies f
ailed
browser.go:128: error 360speed find bookmark file failed, ERR:find Bookmarks fai
led
browser.go:128: error 360speed find cookie file failed, ERR:find Cookies failed
browser.go:128: error 360speed find history file failed, ERR:find History failed

browser.go:128: error 360speed find password file failed, ERR:find Login Data fa
iled

```

**Desktop (please complete the following information):**
 - OS Name 操作系统名称: Windows 7 64bit
 - Browser Name 浏览器名称:QQ浏览器
 - Browser Version 浏览器版本:10.6.4212.400

**Additional context**

QQ浏览器中导出的密码是空的（只有列标题）

此外QQ浏览器中导出的书签虽然有数据，但似乎被经过伪造

Chrome数据导出正常，但是360浏览器的数据完全没导出（连空的csv都没有产生）

运行的hacker-browse版本为hacker-browserr-data-v0.2.7的Release中二进制文件，非自行编译

**Comment by KJZH001** [comment]
![QQ浏览器截图20201114181346.png](https://icdn.7t5j.cn/2020/11/14/2195948cf6470.png)
![QQ浏览器截图20201114181150.png](https://icdn.7t5j.cn/2020/11/14/ecb9caaa2321b.png)
这里是我的浏览器书签部分截图和导出的内容截图，希望能够对您修复bug有所帮助

**Comment by moonD4rk** [comment]
暂不支持 `360安全浏览器（绿色）`，支持的是 `360极速浏览器（彩色）`。 QQ浏览器的后面我会看看，感谢提供版本信息。

**Comment by moonD4rk** [comment]
无法复现你QQ浏览器无法导出的情况，我在本机测试没问题。
 `qqbrowser://version/`
```
QQ浏览器	10.6.4212.400
操作系统	Windows
...
可执行文件路径	C:\Program Files (x86)\Tencent\QQBrowser\QQBrowser.exe
个人资料路径	C:\Users\User\AppData\Local\Tencent\QQBrowser\User Data\Default
```

`书签有伪造`是浏览器会内置一些商业网站的书签，导出的时候会一起导出。


<img width="755" alt="Screen Shot 2020-11-16 at 13 54 27" src="https://user-images.githubusercontent.com/24284231/99217694-a9037d80-2813-11eb-9de3-5766e9c81ce6.png">

**Comment by KJZH001** [comment]
> 无法复现你QQ浏览器无法导出的情况，我在本机测试没问题。
> `qqbrowser://version/`
> 
> ```
> QQ浏览器	10.6.4212.400
> 操作系统	Windows
> ...
> 可执行文件路径	C:\Program Files (x86)\Tencent\QQBrowser\QQBrowser.exe
> 个人资料路径	C:\Users\User\AppData\Local\Tencent\QQBrowser\User Data\Default
> ```
> 
> `书签有伪造`是浏览器会内置一些商业网站的书签，导出的时候会一起导出。
> 
> <img alt="Screen Shot 2020-11-16 at 13 54 27" width="755" src="https://user-images.githubusercontent.com/24284231/99217694-a9037d80-2813-11eb-9de3-5766e9c81ce6.png">

那么需要我进一步提供相关的信息吗，比如说完整的chrome://version中的内容

此外关于```书签有伪造```这个问题，其实并不是商业书签和普通书签一起导出了，而是只导出了csv截图中的这些（而且都是不是我收藏夹中有的内容）
您可以观察一下在我的浏览器书签截图中右下方的滚动条，应该不难发现我的浏览器书签的条目是远多于截图中的条目数量的

此前我自己也去测试了一下，发现似乎是hack-browser-data将360安全浏览器中的书签内容误当做QQ浏览器中的书签导出了（原因我目前还没有找到），因为导出的内容基本都能对上

**Comment by KJZH001** [comment]
此外我还有个问题想要向您询问一下
具体的内容您可以参考下方的截图
在浏览器的设置中我无法查看到保存的账号和密码（从某次QQ浏览器更新后出现，此前正常）
但是保存和自动填充账号密码的功能却可以正常使用，所以个人猜测此bug的产生是否和这个有关
请问在您尝试复现这个bug的过程中有出现过这种现象吗？
![QQ浏览器截图20201120193638.png](https://icdn.7t5j.cn/2020/11/20/e4620cd719f05.png)
![QQ浏览器截图20201120193557.png](https://icdn.7t5j.cn/2020/11/20/9b70d69cfd580.png)

**Comment by KJZH001** [comment]
由于这几天我在学校，所以无法及时回复
抱歉让您久等了

**Comment by moonD4rk** [comment]
感觉像是浏览器 Bug，没有遇到过具体情况，不太好复现。

浏览器数据保存文件路的径可以通过在标签栏输入 `qqbrowser://version/` 和 `360SE://version` 查看对应字段，可以对比文件夹看看是否有明显异常。建议更换成更为现代的浏览器。

**Comment by KJZH001** [comment]
> 感觉像是浏览器 Bug，没有遇到过具体情况，不太好复现。
> 
> 浏览器数据保存文件路的径可以通过在标签栏输入 `qqbrowser://version/` 和 `360SE://version` 查看对应字段，可以对比文件夹看看是否有明显异常。建议更换成更为现代的浏览器。

好的，下面的是我的浏览器的一些版本信息
关于更换浏览器也其实不是没有考虑过，只是没有找到合适的方法来更换，而且还有就是习惯和曾经的浏览器数据方面的考虑
要是这么多年的浏览数据提不出来没法迁移到chrome上那用起来也应该会挺难受的是吧

```
QQ浏览器 | 10.7.4307.400
操作系统 | Windows
...

可执行文件路径 | C:\Program Files (x86)\TSoft\QQSrow\QQBrowser.exe
个人资料路径 | C:\Users\Administrator\AppData\Local\Tencent\QQBrowser\User Data\Default
```

```

360安全浏览器 | 12.2.1564.0 (正式版本) （32 位）
...
操作系统 | Windows 7 Service Pack 1 (Build 7601)
...
可执行文件路径 | C:\Users\Administrator\AppData\Roaming\360se6\Application\360se.exe
个人资料路径 | c:\users\administrator\appdata\roaming\360se6\User Data\Default
```

**Comment by moonD4rk** [comment]
QQ 浏览器的问题没法复现，看文件夹没啥大问题。
360 解密可以看看这个程序，https://github.com/hayasec/360SafeBrowsergetpass
