### ISSUE TITLE
Doesn't extract passwords from Firefox

### ISSUE THREAD

**Issue by dennyvsdev** [moonD4rk/HackBrowserData#43]
I am using both **release 0.2.8** and my build from latest source with this commands:

- .\hack-browser-data.exe -b all -f json -dir results -cc
- .\hack-browser-data.exe -b firefox -f json -dir results -cc
- .\hack-browser-data.exe -b all

It does find Everthing on Edge (version 86.0.622.69) and chrome (version 86.0.4240.198) but no luck in finding passwords from firefox.

**Desktop :**
 - OS Name : Windows 10 2004
 - Browser Name : FireFox
 - Browser Version : 78.0.1 and 82.0.3 (latest)

Additional context :
I have tried both running command in privileged mode and while firefox processes are terminated.
Also logs aren't clear and too much go error in case it doesn't find anything. For firefox and this command `.\hack-browser-data.exe -b all -f json -dir results -cc` logs look like this:
`decrypt_windows.go:122: error asn1: structure error: tags don't match (16 vs {class:0 tag:4 length:20 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} SequenceC @2
parse.go:523: error decrypt meta data failed asn1: structure error: tags don't match (16 vs {class:0 tag:4 length:20 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} SequenceC @2
cmd.go:77: error asn1: structure error: tags don't match (16 vs {class:0 tag:4 length:20 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} SequenceC @2
[x]:  Get 0 passwords, filename is results/firefox_password.json
[x]:  Get 27 bookmarks, filename is results/firefox_bookmark.json
[x]:  Get 854 cookies, filename is results/firefox_cookie.json
[x]:  Get 21277 history, filename is results/firefox_history.json`

**Comment by dennyvsdev** [comment]
Hey. I have tested the 0.3.2 version and everything is perfect (even firefox history, Cookie, and bookmarks) but the output JSON for firefox passwords is empty and it says `null`. I couldn't make it to work. Should those passwords be synced to the Mozilla account?

Firefox version : 84.0.2

**Comment by dijiang** [comment]
> Hey. I have tested the 0.3.2 version and everything is perfect (even firefox history, Cookie, and bookmarks) but the output JSON for firefox passwords is empty and it says `null`. I couldn't make it to work. Should those passwords be synced to the Mozilla account?
> 
> Firefox version : 84.0.2

have the same problem on Mac

**Comment by rnerone36** [comment]
What does it extract yours? Lol that's Firefox did to me

**Comment by moonD4rk** [comment]
Hi, I think I've fixed the firefox password decryption failure problem. if it's still wrong, you can reopen this issue.

commit after f8dc8bb

**Comment by dennyvsdev** [comment]
Thank u so much for your efforts. It is fixed now.
