### ISSUE TITLE
When the edge or chrome browser is running, the cookie fails to be obtained. Procedure

### ISSUE THREAD

**Issue by netpr1s0ner** [moonD4rk/HackBrowserData#446]
## Describe the bug
When the edge or chrome browser is running, the cookie fails to be obtained. Procedure

## Desktop (please complete the following information):
Select the operating system(s) you are using:
- [👌] Windows

- OS Version: windows10
- OS Architecture: amd-64
- Browser Name:  chrome, firefox and Edg
- Browser Version: all

## Additional Details
cookie file occupancy.

## Suggest
 Copy cookies by volume shadow copy

**Comment by moonD4rk** [comment]
Next version [v0.5.0](https://github.com/moonD4rk/HackBrowserData/issues/437) including the function of copy locked files.
