### ISSUE TITLE
Chromium-based browsers find wrong user

### ISSUE THREAD

**Issue by Aquilao** [moonD4rk/HackBrowserData#447]
## Describe the bug

I found that when running the program on my computer, a "def" user was identified, which did not exist. 
I tracked down the folder and found that the location was under `AppData\Local\Google\Chrome\User Data\Default\Storage\ext\nmmhkkegccagdldgiimedpiccmgmieda\def`, which was not a user configuration. 
The solution was to add an exclusion to the `chromiumWalkFunc` function, and I will submit a PR later to fix this problem.

## Log Output
![image](https://github.com/user-attachments/assets/2369153e-03ce-47ba-8572-c17e1813fabc)

## Expected vs Actual Behavior
Describe what you expected to happen and what actually happened.

## Desktop (please complete the following information):
Select the operating system(s) you are using:
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by moonD4rk** [comment]
Closed By https://github.com/moonD4rk/HackBrowserData/pull/448
