### ISSUE TITLE
macOS Big Sur 双击直接停止运行，退出了

### ISSUE THREAD

**Issue by shyboy** [moonD4rk/HackBrowserData#45]
macOS Big Sur
版本11.0.1
直接双击后显示
[1]    11091 killed     /Users/sunshy/Desktop/hack-browser-data
Saving session...completed.
[进程已完成]
[示意](https://files.catbox.moe/hiwznk.png)

**Comment by moonD4rk** [comment]
ARM 版本的 Mac 需要自己编译。

**Comment by moonD4rk** [comment]
@shyboy macOS 11.1 下无法正常打开已编译好的二进制文件看起来是 upx 压缩的问题，不使用  upx 使用原生的编译是没有问题的。
 https://github.com/moonD4rk/HackBrowserData/issues/60#issuecomment-769561970
