### ISSUE TITLE
Export Results

### ISSUE THREAD

**Issue by YasirAsim** [moonD4rk/HackBrowserData#46]
Hi, Thank you very much for this code. Is there any way to get all the results through email? i.e when someone double clicks on that  file, the results could be send to us through email?

**Comment by moonD4rk** [comment]
I don't think it's a good idea to add the feature to send an email. The core of this software is for decryption and forensics. It already provides compressed results to `.zip` (-cc). if you really need this, you can implement the feature yourself to send the zip via email or some other methods.
