### ISSUE TITLE
results saved not .json format to import 

### ISSUE THREAD

**Issue by mixpro309** [moonD4rk/HackBrowserData#47]
window 10 , firefox and chrome lastest version 
program run well but results saved into excel format 
I can't import it because it's not .json format 
Can you help me to fix it ? 
![coookies](https://user-images.githubusercontent.com/74844385/100358071-9289cd00-3030-11eb-91e3-1ad83d2d6441.PNG)

**Comment by xaitax** [comment]
-f json

**Comment by moonD4rk** [comment]
`hack-browser-data.exe -f json` use this command on your windows console.
