### ISSUE TITLE
The browser cannot detect data without being installed in the default location

### ISSUE THREAD

**Issue by joneyue** [moonD4rk/HackBrowserData#53]
**Describe the bug**
描述一下遇到的 Bug，和对应的报错信息 `./hack-browser-data -vv`

The browser cannot detect data without being installed in the default location
**Desktop (please complete the following information):**
 - OS Name 操作系统名称: 
 - Browser Name 浏览器名称:
 - Browser Version 浏览器版本:

**Additional context**
其他有用的信息

**Comment by joneyue** [comment]
could u add gui and select location by myself

**Comment by Not-Cyrus** [comment]
#40

**Comment by moonD4rk** [comment]
duplicate with https://github.com/moonD4rk/HackBrowserData/issues/40
