### ISSUE TITLE
[BUG] mac交叉编译的问题

### ISSUE THREAD

**Issue by fwf24** [moonD4rk/HackBrowserData#56]
**Describe the bug**
描述一下遇到的 Bug，和对应的报错信息 `./hack-browser-data -vv`

**Desktop (please complete the following information):**
 - OS Name 操作系统名称: win10 win7
 - Browser Name 浏览器名称:
 - Browser Version 浏览器版本:

**Additional context**
其他有用的信息

mac goland中交叉编译win可执行文件exe，打包出来后文件体积6.29M。
无论普通运行还是管理员运行，都无法获取所有值，所有的csv文件都是1kb，打开是空白的。

编译命令 
CGO_ENABLED=0 GOOS=windows  GOARCH=amd64  go  build  main.go

其中一段的报错结果
cmd.go:68: error Chrome secret key path is empty
browser.go:138: error Chrome find bookmark file failed, ERR:find Bookmarks failed
browser.go:138: error Chrome find cookie file failed, ERR:find Cookies failed
browser.go:138: error Chrome find history file failed, ERR:find History failed
browser.go:138: error Chrome find password file failed, ERR:find Login Data failed
browser.go:138: error Chrome find creditcard file failed, ERR:find Web Data failed
cmd.go:68: error Microsoft Edge secret key path is empty
browser.go:138: error Microsoft Edge find bookmark file failed, ERR:find Bookmarks failed

**Comment by moonD4rk** [comment]
编译时需要 CGO，详细看下面。 https://github.com/moonD4rk/HackBrowserData/blob/master/README_ZH.md#%E8%B7%A8%E5%B9%B3%E5%8F%B0%E7%BC%96%E8%AF%91

**Comment by fwf24** [comment]
> 编译时需要CGO，详细看下面。[https://github.com/moonD4rk/HackBrowserData/blob/master/README_ZH.md#%E8%B7%A8%E5%B9%B3%E5%8F%B0%E7% BC％96％E8％AF％91](https://github.com/moonD4rk/HackBrowserData/blob/master/README_ZH.md#%E8%B7%A8%E5%B9%B3%E5%8F%B0%E7%BC%96%E8%AF%91)

已经解决，谢谢大哥指导。
如果能适配更多浏览器就炒鸡完美~笔芯
