### ISSUE TITLE
Enhance the "--profile-dir-path" options to make it easier

### ISSUE THREAD

**Issue by MrNonoss** [moonD4rk/HackBrowserData#57]
Hi there,

With the new 0.3.1 version, comes the possibility to provide a custom profile dir path for the browser data collection. That is very useful.

The bad effect of it is that we have to provide a very detailed path for each browser. It is not possible to select all browsers.
Could it be possible to set a custom "Users" path and let the tool work like it would if it was the regular path?

For exemple:
`.\hack-browser-data.exe --vv --cc -b all -p G:\Users`

As of now, this command returns the following error:
`cmd.go:52: error can't select all browser, pick one from chrome|chrome-beta|edge|qq|firefox|360|brave|opera|opera-gx|vivaldi with -b flag`

Many thanks

**Comment by moonD4rk** [comment]
Thank you for your advice. I have considered not using `-b`  flag to specify a browser, The reason for this is that some browsers require `-k` to specify the path to the secret key file, while others do not. The current method is to use `-b` to select a browser

<img width="1109" alt="browser path" src="https://user-images.githubusercontent.com/24284231/103261397-66b98880-49dc-11eb-8768-05c90e838d5e.png">

I will find out if there is a better way to solve this problem.
