### ISSUE TITLE
为啥不编译个win32的，都向下兼容啊。好多内网机子是32位的，反而64用的少呀？

### ISSUE THREAD

**Issue by Laura0xiaoshizi** [moonD4rk/HackBrowserData#58]
**Describe the bug**
描述一下遇到的 Bug，和对应的报错信息 `./hack-browser-data -vv`
为啥不编译个win32的，都向下兼容啊。好多内网机子是32位的，反而64用的少呀？

**Desktop (please complete the following information):**
 - OS Name 操作系统名称: 
 - Browser Name 浏览器名称:
 - Browser Version 浏览器版本:

**Additional context**
其他有用的信息

**Comment by rnerone36** [comment]
English please

**Comment by kasusa** [comment]
> English please

he/she want to have a win32 exe file.

**Comment by lc6464** [comment]
No need? There are more x64 users than x86 users now.
没什么必要吧？现在用 x64 的比用 x86 的多多了。

Or you can choose to compile it yourself, so that the security software will not report the virus all the time.
或者你也可以选择自己编译，这样安全软件也不会一直报毒。
