### ISSUE TITLE
编译后使用upx压缩存在问题

### ISSUE THREAD

**Issue by NoneNotNull** [moonD4rk/HackBrowserData#60]
使用如下两种方式编译生成的二进制文件均可运行
`go build -ldflags "-w" .`
`go build -ldflags "-s" .`

但是上述方式生成的二进制文件无法使用upx进行压缩（如果go编译的时候不使用-w或者-s，压缩后又可以运行），运行文件直接就killed了
`upx HacBrowserData`

能参考一下你的命令么

**Comment by moonD4rk** [comment]
你操作系统是 macOS 吗？我在 Mac 上测试同样在 upx 压缩后无法运行程序。
```shell
$ go build -ldflags "-w -s" .

$ ./hack-browser-data -h
NAME:
   hack-browser-data - Export passwords/cookies/history/bookmarks from browser
...

$ upx hack-browser-data
...

$ ./hack-browser-data -h
[1]    75978 killed     ./hack-browser-data -h


```

```
OS:  macOS
Version: 11.1
Processer: 2.6 GHz 6-Core Intel Core i7
```

其他平台测试没问题。

**Comment by NoneNotNull** [comment]
是的  macOS的系统

**Comment by moonD4rk** [comment]
最新的 Release 不再使用 `upx` 对程序做压缩，所以在 MacOS 上运行时不会出现这个 upx 的问题了。
