### ISSUE TITLE
360 Speed Browser	不能导出任何数据

### ISSUE THREAD

**Issue by no13list** [moonD4rk/HackBrowserData#64]
**Describe the bug**
描述一下遇到的 Bug，和对应的报错信息 `./hack-browser-data -vv`

**Desktop (please complete the following information):**
 - OS Name 操作系统名称: win10
 - Browser Name ：360 Speed Browser

 - Browser Version 浏览器版本:版本号：12.0.1592.0
内核版本：78.0.3904.108

**Additional context**
其他有用的信息

**Comment by moonD4rk** [comment]
duplicate https://github.com/moonD4rk/HackBrowserData/issues/65
