### ISSUE TITLE
360 Speed Browser	Cannot decrypt any data

### ISSUE THREAD

**Issue by no13list** [moonD4rk/HackBrowserData#65]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS Name : win10
 - Browser Name :360 Speed Browser
 - Browser Version 12.0.1592.0
chromium：78.0.3904.108

**Comment by moonD4rk** [comment]
你指的是 [360急速浏览器](https://browser.360.cn/ee/index.html) 还是 [360安全浏览器](https://zh.wikipedia.org/wiki/360%E5%AE%89%E5%85%A8%E6%B5%8F%E8%A7%88%E5%99%A8)？

此工具不支持「360安全浏览器」密码的导出，如果需要可以看看这个项目 
https://github.com/hayasec/360SafeBrowsergetpass

如果是「360急速浏览器 」，请使用以下命令，并将对应的报错信息发出来
```
.\hack-browser-data.exe -b 360 -vv
```

**Comment by xxitalyan** [comment]
🤳👮‍♂️

**Comment by moonD4rk** [comment]
此 issues 暂时关闭，如有后续可以提交评论后再打开。
