### ISSUE TITLE
建议隐藏找不到浏览器数据报错信息。 It is recommended to hide the error message that the browser data cannot be found.

### ISSUE THREAD

**Issue by lc6464** [moonD4rk/HackBrowserData#71]
**Describe the bug**
描述一下遇到的 Bug，和对应的报错信息 `./hack-browser-data -vv`

当找不到一种浏览器时报错，例如当找不到360极速浏览器时：
`browser.go:144: error 360speed find password file failed, ERR:find Login Data failed`
建议隐藏此报错信息。

An error is reported when a browser cannot be found, for example, when 360 speed cannot be found:
`browser.go:144: error 360speed find password file failed, ERR:find Login Data failed`
It is recommended to hide this error message.

**Desktop (please complete the following information):**
 - OS Name 操作系统名称: `Windows 10`
 - Browser Name 浏览器名称: more than one... 不止一个……
 - Browser Version 浏览器版本: more than one... 不止一个……

**Additional context**
其他有用的信息
`Windows 10 20H2 x64 Enterprise`
`go version go1.15.8 windows/amd64`
自行编译。Compile by myself.

**Comment by moonD4rk** [comment]
感谢建议，修改了错误信息的日志等级。
