### ISSUE TITLE
[Improvement] CHANGELOG

### ISSUE THREAD

**Issue by xaitax** [moonD4rk/HackBrowserData#75]
Hi, 

would be awesome if you could also establish a file for the CHANGELOG with all the (great) frequent changes of each version.

I think it would be helpful for everyone to track what is and has happened.

**Comment by moonD4rk** [comment]
Thanks for the suggestion, I will add it as soon as possible.

**Comment by moonD4rk** [comment]
Add changelog via github auto-generated logs, thanks to everyone who helped make this project better.
