### ISSUE TITLE
运行需要输入密码

### ISSUE THREAD

**Issue by w2n1ck** [moonD4rk/HackBrowserData#77]
macos，运行需要输入root密码，否则导出的数据无明文密码。如果需要输入密码那这项目还有啥用？

**Comment by moonD4rk** [comment]
[Mac](https://github.com/moonD4rk/HackBrowserData/blob/master/README_ZH.md#macos) 下就是这样，系统安全性设置问题。

**Comment by U97F3** [comment]
这提问也是绝了，上升到项目还有啥用来了。。。
