### ISSUE TITLE
windows defender 报毒

### ISSUE THREAD

**Issue by ibin7777** [moonD4rk/HackBrowserData#80]
**Describe the bug**
描述一下遇到的 Bug，和对应的报错信息 `./hack-browser-data -vv`
windows defender识别hack_browser_data.exe文件为木马Trojan:Win32/Ymacco.AA26

**Desktop (please complete the following information):**
 - OS Name 操作系统名称:
版本:	Windows 10 家庭中文版
版本号:	20H2
安装日期:	‎2020/‎8/‎24
操作系统内部版本:	19042.962
体验:	Windows Feature Experience Pack 120.2212.2020.0

**Additional context**
其他有用的信息

**Comment by moonD4rk** [comment]
这属于正常现象，可查阅[此条文档](https://github.com/moonD4rk/HackBrowserData/blob/master/README_ZH.md#%E5%AE%89%E8%A3%85)，建议将运行程序添加到白名单里面
也可以参考其他衍生项目
1. https://github.com/S3cur3Th1sSh1t/Sharp-HackBrowserData 
2. https://github.com/idiotc4t/Reflective-HackBrowserData

**Comment by moonD4rk** [comment]
duplicate with https://github.com/moonD4rk/HackBrowserData/issues/35#issuecomment-723461867
