### ISSUE TITLE
这个是不是不适用 chrome dev

### ISSUE THREAD

**Issue by ShaoLongFei** [moonD4rk/HackBrowserData#82]
**Describe the bug**
执行命令后没有文件生成

**Desktop (please complete the following information):**
 - OS Name 操作系统名称:  MacOS Big Sur 11.0.1
 - Browser Name 浏览器名称: chrome dev
 - Browser Version 浏览器版本: 92

**Additional context**
其他有用的信息:
shaolongfei@shaolongfeis-MacBook-Pro ~ % /Users/shaolongfei/Downloads/hack-browser-data-v0.3.5-osx-64bit/hack-browser-data ; exit;
zsh: killed     
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by moonD4rk** [comment]
Mac 系统下使用编译好的包运行会有 BUG，具体可看此条 Issues https://github.com/moonD4rk/HackBrowserData/issues/60#issuecomment-769561970

自己编译，不使用 upx 压缩就没有问题
