### ISSUE TITLE
[BUG] firefox can't find url in bookmarks

### ISSUE THREAD

**Issue by pretech86** [moonD4rk/HackBrowserData#84]
**Describe the bug**
描述一下遇到的 Bug，和对应的报错信息 `./hack-browser-data -vv`
 .\hack-browser-data.exe -b firefox -vv  -dir results -cc

**Desktop (please complete the following information):**
 - OS Name windows
 - Browser Name firefox
 - Browser Version last

i didn't get the data like url in bookmarks 
**Additional context**
其他有用的信息

**Comment by moonD4rk** [comment]
yep, firefox can not getting bookmark is a bug, I will try to fix it in the future.
