### ISSUE TITLE
Why not for 32 bits Windows?

### ISSUE THREAD

**Issue by hy0zen** [moonD4rk/HackBrowserData#85]
The software is great, but why don't exist the 32 bits version for Windows?

 - OS Name: Windows
 - Browser Name: Chrome

**Comment by moonD4rk** [comment]
This is a github actions issue, using the default github actions ubuntu runner to cross-platform compile windows 32 programs will panic an error, I do not have enough time and energy to complete this function.

I will try to add this 32-bit runner to the release in the future,  you can clone the source code and compile the 32-bit version on your local computer.
