### ISSUE TITLE
Error go-sqlite3 in windows

### ISSUE THREAD

**Issue by Tanato99** [moonD4rk/HackBrowserData#86]
- OS Name: Windows 10 64 bit

Hi, i tried to build but i reveived this error:

`C:\Users\MyPC>git clone https://github.com/moonD4rk/HackBrowserData
Cloning into 'HackBrowserData'...
remote: Enumerating objects: 1258, done.
remote: Counting objects: 100% (551/551), done.
remote: Compressing objects: 100% (405/405), done.
remote: Total 1258 (delta 159), reused 515 (delta 123), pack-reused 707 eceiving objects:  97% (1221/1258)
Receiving objects: 100% (1258/1258), 1.80 MiB | 4.63 MiB/s, done.
Resolving deltas: 100% (625/625), done.

C:\Users\MyPC>cd HackBrowserData

C:\Users\MyPC\HackBrowserData>go get -v -t -d ./...
go: downloading github.com/godbus/dbus/v5 v5.0.3
go: downloading github.com/ppacher/go-dbus-keyring v1.0.1
go: downloading github.com/tidwall/gjson v1.6.0
go: downloading golang.org/x/crypto v0.0.0-20200604202706-70a84ac30bf9
go: downloading github.com/jszwec/csvutil v1.3.0
go: downloading github.com/mattn/go-sqlite3 v1.14.0
go: downloading github.com/urfave/cli/v2 v2.2.0
go: downloading github.com/tidwall/pretty v1.0.0
go: downloading github.com/tidwall/match v1.0.1
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/mattn/go-sqlite3 v1.14.7

C:\Users\MyPC\HackBrowserData>go build
 github.com/mattn/go-sqlite3
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in`

**Comment by moonD4rk** [comment]
Since the go-sqlite3 library is used, go build requires the `CGO` flag enabled.
```
CGO_ENABLED=1 go build
```

If you don't have gcc installed, you need to download it from here ↓

https://jmeubank.github.io/tdm-gcc/
