### ISSUE TITLE
360极速浏览器

### ISSUE THREAD

**Issue by lant1s** [moonD4rk/HackBrowserData#89]
**Describe the bug**
描述一下遇到的 Bug，和对应的报错信息 `./hack-browser-data -vv`
360极速浏览器无法导出密码

![image](https://user-images.githubusercontent.com/50098629/132345364-bf8acc30-8d24-45f3-a529-b898f1867032.png)

**Desktop (please complete the following information):**
 - OS Name 操作系统名称: windows 10
 - Browser Name 浏览器名称:360极速浏览器
 - Browser Version 浏览器版本:360cse_11.0.2216.0、360cse_13.5.1010.0

**Additional context**
其他有用的信息

**Comment by FlashloverAgustin** [comment]
期待修复，有个网站的密码和账号都忘记了，没有邮箱系统现在进不去用不了这个网站sos

**Comment by moonD4rk** [comment]
Duplicated with #155
