### ISSUE TITLE
Credit Card Information Is not Showing Up

### ISSUE THREAD

**Issue by cartiiii** [moonD4rk/HackBrowserData#97]
It says 0 credit cards everytime, also on different pc s. Can you please fix this

**Comment by moonD4rk** [comment]
Tell me your browser and OS's version, and make sure your credit card information is saved in your browser.

**Comment by raypun78** [comment]
> Tell me your browser and OS's version, and make sure your credit card information is saved in your browser.

mainly I use chrome and edge(latest version) and windows 10 latest. I also used this on a few other pc s and there were saved cards in chrome or edge. but none of them were noticed out. thank you for response

**Comment by moonD4rk** [comment]
Duplicate with https://github.com/moonD4rk/HackBrowserData/issues/114
