### ISSUE TITLE
Is it because of my misoperation

### ISSUE THREAD

**Issue by Yihsiwei** [moonD4rk/HackBrowserData#99]
`hackbrowser.exe -b chrome -f console`
I used the above command, and the result is not correct. Is it because the chrome version is too new
version:95.0.4638.69
Or is it because the order is wrong
![image](https://user-images.githubusercontent.com/59053987/140959762-5c6461ff-8d80-49e7-8fe2-82514550ca62.png)

**Comment by moonD4rk** [comment]
use `./hack-browser-data.exe -vv  -b chrome -f console` and tell me the output.

**Comment by Yihsiwei** [comment]
> use `./hack-browser-data.exe -vv -b chrome -f console` and tell me the output.

![image](https://user-images.githubusercontent.com/59053987/141056924-68e8be72-060f-4fab-8c6a-da37fc3ffc30.png)

**Comment by moonD4rk** [comment]
It's fixed in [v0.4.0](https://github.com/moonD4rk/HackBrowserData/releases), reopen if this bug still happened.
